### ISSUE TITLE
jcomments-4 seem working

### ISSUE THREAD

**Issue by fuzmic2** [exstreme/Jcomments-4#1]
Hi guys
get get the codes zip from here, seem to be working at installation,  will test out fully soon.  THANK YOU.

**Comment by fuzmic2** [comment]
The component menu is working is except when i try to add a new similie.  This is minor problem the the major error is when an article try to incorporate JComments (sse image)
![jc4-err1](https://user-images.githubusercontent.com/16586815/134864859-82452861-b658-4c8d-9222-a58dd47ceecb.jpg)

**Comment by Globulopolis** [comment]
@fuzmic2 be patient. Not only smiles not working. It's many problems in other places in code.

**Comment by fuzmic2** [comment]
Certainly i am at peace as you dig in deep ... Rest assured. Thanks and
Regards
