### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by phnoel** [exstreme/Jcomments-4#100]
Hello,
How to get a good translation in French?
See here : https://weblim.go.yo.fr/avis
Thank you for your help
Philippe

**Comment by exstreme** [comment]
Hello, what you mean about good translation? What is problem now?

**Comment by Globulopolis** [comment]
> Hello, How to get a good translation in French? See here : https://weblim.go.yo.fr/avis Thank you for your help Philippe

If you upgrade from previous Joomla 3 version, you need to add some messages for french language. Go to `administrator/index.php?option=com_config&view=component&component=com_jcomments`, click on `Messages` tab, select `French` and add some translations.

And are you sure using the latest component version?

**Comment by phnoel** [comment]
I did the installation directly from version 4. The language is set to French.
Well, the words are not translated and there are two error messages
![1](https://user-images.githubusercontent.com/106807928/177213923-18255f49-2e99-4177-8ff3-e18922ed2a12.jpg)

**Comment by Globulopolis** [comment]
> I did the installation directly from version 4 (4.0.18). The language is set to French.
> Well, the words are not translated and there are two error messages
> ![1](https://user-images.githubusercontent.com/106807928/177213923-18255f49-2e99-4177-8ff3-e18922ed2a12.jpg)
> 

Show a screenshot of the "Messages" tab.

**Comment by phnoel** [comment]
here it is
![2](https://user-images.githubusercontent.com/106807928/177270293-015739d1-9b2a-434d-a92b-3991a73999d9.jpg)

**Comment by exstreme** [comment]
You should have all translation files (for plugin, component etc) in your fr folder

**Comment by Globulopolis** [comment]
@phnoel you have an outdated component files. Looks like something went wrong during upgrade. Try to reinstall component.

**Comment by phnoel** [comment]
OK, and where can i download the latest component up to date ? (url, name of the zip file please)
As a precaution, should I uninstall everything first?

**Comment by exstreme** [comment]
Yes, uninstall first.
https://github.com/exstreme/Jcomments-4/releases/latest

**Comment by phnoel** [comment]
How can I save the comments before uninstalling everything?

**Comment by Globulopolis** [comment]
> How can I save the comments before uninstalling everything?

If you uninstalling only jcomments, comments will not be deleted. But anyway - do a database backup.

**Comment by phnoel** [comment]
it's better (I don't have the error messages anymore), but still untranslated labels and the "messages" tab not giving access to the fields to be translated.

**Comment by Globulopolis** [comment]
> untranslated labels

You need to add French translation first.


> "messages" tab not giving access to the fields to be translated

What does it mean?

Try to add messages for `All` language and for `French`.

**Comment by phnoel** [comment]
I downloaded the translation..and it doesn't work.
![3](https://user-images.githubusercontent.com/106807928/177343295-67ef6053-b4d8-46c3-bc18-1a388a616e50.jpg)

Here is the file
[traduction.pdf](https://github.com/exstreme/Jcomments-4/files/9046890/traduction.pdf)

**Comment by Globulopolis** [comment]
> Only these fields appear.

These fields only for some messages displayed to user. It's not a translations.


> I downloaded the translation..and it doesn't work.

rename file to `com_jcomments.ini`

**Comment by phnoel** [comment]
Done, but it didn't change anything
Is it the good folder ? weblim.go.yo.fr/public_html/language/fr-FR/com_jcomments.ini

**Comment by Globulopolis** [comment]
> Is it the good folder

Yes.

Some language strings is not available on french due to an outdated french translations. Compare English and your French translation files and you will see the difference.

**Comment by phnoel** [comment]
there is no file com_jcomments.ini in the en-GB directory !

**Comment by phnoel** [comment]
It's the same thing !

**Comment by exstreme** [comment]
Update to v4.0.22 pls

**Comment by phnoel** [comment]
YES ! It works now. Many thanks...

**Comment by phnoel** [comment]
Why not! Send me files to  translate 
---- Message d'origine ----

**Comment by Globulopolis** [comment]
> Why not! Send me files to translate

http://libra.ms/share/files/to_translate.zip

**Comment by phnoel** [comment]
Hi,

here are the translated files

Good reception

Philippe


De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] translation (Issue #100)
Date : 11/10/2022 11:01:57 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


Why not! Send me files to translate

http://libra.ms/share/files/to_translate.zip

**Comment by Globulopolis** [comment]
> Hi, here are the translated files Good reception Philippe

Look like something went wrong and translated files isn't attached to the message.

**Comment by phnoel** [comment]
Are you sure?

I have attached a .zip file

I'll send it to you, just in case...


De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] translation (Issue #100)
Date : 19/11/2022 19:30:43 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


Hi, here are the translated files Good reception Philippe

Look like something went wrong and translated files isn't attached to the message.

**Comment by Globulopolis** [comment]
> Are you sure? I have attached a .zip file

Yes, I'm sure. Go to GitHub and attach file in reply form. I think the zip isn't attached properly when reply to email.

**Comment by phnoel** [comment]
The files
[jcomments to_translate.zip](https://github.com/exstreme/Jcomments-4/files/10048070/jcomments.to_translate.zip)
