### ISSUE TITLE
Проблемы после установки/миграции

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#102]
Итак, был сайт на Joomla 3.
Помня вот этот опыт (https://github.com/exstreme/Jcomments-4/issues/85#issuecomment-1131291881), 
сделал вот так:
перед миграцией на четверку, переключился на английский язык в админке, отфильтровал все расширения по фразе jcomments и деинсталлировал.
во время деинсталляции прежней версии получил такое:
<img width="1378" alt="Снимок экрана 2022-07-21 в 18 29 18" src="https://user-images.githubusercontent.com/3432048/180390506-29a52985-ec5d-4635-97ef-5d70cda4abee.png">

но больше в списке расширений jcomments не было. 
обновился до J4 и поставил JComments 4.0.22.

Итого:
правила комментов с чекбоксом не отображаются (ссылка на проблему выше)
также я не вижу поддеркжи hCaptcha - в настройках нет такой опции.

исходя из чего делаю вывод:
либо деинсталляция/установка была некорректной, либо у вас пакет 4.0.22 не включает в себя заявленные правки.
скачивал отсюда:
https://github.com/exstreme/Jcomments-4/releases

<img width="1380" alt="Снимок экрана 2022-07-22 в 10 51 21" src="https://user-images.githubusercontent.com/3432048/180391106-3a574168-894a-458a-b47f-2def6307f28c.png">

<img width="1163" alt="Снимок экрана 2022-07-22 в 10 52 10" src="https://user-images.githubusercontent.com/3432048/180391240-e072b399-b423-4ef5-b7e1-34ce3b75e0d8.png">

**Comment by exstreme** [comment]
А сам плагин hCaptcha установлен и включен?

**Comment by Sulpher** [comment]
упс. плагин не поставлен :-) спасибо, что обратил внимание.
но мне он пока не нужен - хотел понять, что с функционалом отображения правил.
посмотрел, физически тут так:
component/site/jcomments.php
if ($policy != '' && $acl->showPolicy())

в настройках приватности для public и для guest правильные параметры:

<img width="1042" alt="Снимок экрана 2022-07-22 в 12 47 13" src="https://user-images.githubusercontent.com/3432048/180413424-fe54633c-d5f7-46db-8b0b-bdd98b5c7ff7.png">

**Comment by exstreme** [comment]
А текст правил прописан?

**Comment by Sulpher** [comment]
да, текст прописан.
<img width="1128" alt="Снимок экрана 2022-07-23 в 13 29 18" src="https://user-images.githubusercontent.com/3432048/180601402-9ca955c6-6451-46f5-84ca-b577ae4d7351.png">

<img width="1073" alt="Снимок экрана 2022-07-23 в 13 32 25" src="https://user-images.githubusercontent.com/3432048/180601482-a316c4c5-853c-4be7-a466-5f772eaf69be.png">


мультиязычности нет, у всего контента  выставлен язык - все.  пробовал и русский поставить - не помогло.
странно....
я все таки склоняюсь, что деинсталляция прошла некорректно и остался какой-то мусор с J3.

кстати, а почему 3 плагина-кнопки?
<img width="1419" alt="Снимок экрана 2022-07-23 в 10 33 20" src="https://user-images.githubusercontent.com/3432048/180601439-7a83cbe7-ebd3-4d32-a2ee-1ca4ff15644e.png">

чем отличаются JComments OFF и JComments LOCK?

**Comment by Sulpher** [comment]
и вот еще что заметил после миграции:
https://github.com/exstreme/Jcomments-4/issues/103

**Comment by Globulopolis** [comment]
> да, текст прописан.

"Условия использования" и "Правила комментирования" это разные настройки.
Первая находится на вкладке "Права", вторая на вкладке "Форма добавления комментариев" -> "Показывать правила".



> кстати, а почему 3 плагина-кнопки?

JComments ON вкючает комментирование для материала;
JComments OFF выключает, вместе с комментариями;
JComments LOCK блокирует добавление новых комментариев, но разрешает их показ.

**Comment by Sulpher** [comment]
спасибо за ответ. 
но не понял - мне нужно вывести чекбокс с правилами. поле Условия использования заполнено. в настройках включено.

Компонент - JComments - настройки  - вид - Показывать флажок "Принять условия использования". - да
Права доступа - Показывать флажок "Принять условия использования". - разрешено
<img width="837" alt="Снимок экрана 2022-07-23 в 16 17 20" src="https://user-images.githubusercontent.com/3432048/180606746-302960cc-fe92-4a1b-9fdf-0fe614bc68e7.png">
<img width="1471" alt="Снимок экрана 2022-07-23 в 16 17 27" src="https://user-images.githubusercontent.com/3432048/180606750-f7c316e2-fce1-4239-8044-7906e595527c.png">
<img width="1144" alt="Снимок экрана 2022-07-23 в 16 17 44" src="https://user-images.githubusercontent.com/3432048/180606754-070a7d0f-5730-4a55-8d0e-31121f9992a3.png">
<img width="988" alt="Снимок экрана 2022-07-23 в 16 18 16" src="https://user-images.githubusercontent.com/3432048/180606762-90134ad3-e985-4bc7-8073-dd601a94b458.png">

 но не отображается.

**Comment by Globulopolis** [comment]
@Sulpher, понял в чем беда. Ошибка в переводе текста разрешения. Переключите флажок в правах на "Запрещено".

**Comment by Sulpher** [comment]
Да, так помогло.  спасибо!
