### ISSUE TITLE
Некорректные данные в таблицах БД после миграции

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#103]
удалил компонент JC, обновил j3 на j4. поставил JC.
иду сюда:

![Снимок экрана 2022-07-23 в 13 34 20](https://user-images.githubusercontent.com/3432048/180601522-a6960b97-a2ce-4435-be94-b7531e1c7075.png)

<img width="1647" alt="Снимок экрана 2022-07-23 в 10 46 06" src="https://user-images.githubusercontent.com/3432048/180601528-9daac25f-4c0f-4cc4-8338-f362e5272b85.png">

нажимаю на исправить. остается только это:
<img width="1651" alt="Снимок экрана 2022-07-23 в 10 46 25" src="https://user-images.githubusercontent.com/3432048/180601534-d2620358-7406-43e5-8223-21e568612f56.png">

и это повторным нажатием кнопки не фиксится.
видимо, изменилась структура таблиц в новой версии.

**Comment by Globulopolis** [comment]
Да, таблицы менялись. Проверьте это поле в таблице. Если оно `VARCHAR(100) NOT NULL DEFAULT ''` то всё нормально, если нет - исправьте вручную.

**Comment by Sulpher** [comment]
посмотрел. в структуре таблицы jcomments_subscriptions нет столбца source.
<img width="1092" alt="Снимок экрана 2022-07-23 в 18 20 56" src="https://user-images.githubusercontent.com/3432048/180611456-fffc155b-80d9-4cb1-a959-eb28b9815895.png">

**Comment by Globulopolis** [comment]
Видимо обновление не прошло нормально. Должно быть так 
![image](https://user-images.githubusercontent.com/740757/180611920-aefae9ca-0266-41bd-a2ca-c637ad86f4aa.png)

**Comment by Sulpher** [comment]
Да, добавил столбец вручную. спасибо!
еще заметил, что после миграции у многих столбцов в таблицах JComments  Collation выставлено как 
 utf8mb3_general_ci вместо utf8mb4_general_ci

если это имеет значение.  нужно ли вносить в компонент какие-то правки по части миграции? 
или урок на github написать с SQL дампом/пошаговой инструкцией для других.
если что -  можно закрывать тикет.

**Comment by Globulopolis** [comment]
> еще заметил, что после миграции у многих столбцов в таблицах JComments Collation выставлено как
> utf8mb3_general_ci вместо utf8mb4_general_ci

utf8mb3_general_ci это тот же utf8_general_ci. Смените на utf8mb4_general_ci.
