### ISSUE TITLE
antispam

### ISSUE THREAD

**Issue by phnoel** [exstreme/Jcomments-4#105]
Hello,
Since a few days, Jcomment's antispam is not efficient anymore. I receive several false messages per day.
Are you aware of this?
Do you have a solution to solve this problem?
Thanks
Kind regards

**Comment by Globulopolis** [comment]
Captcha should help with this.

**Comment by phnoel** [comment]
Sorry, but even recaptcha is no longer effective. I even modified the key without getting a better result

**Comment by Globulopolis** [comment]
Hmm... Need some dig into it.

**Comment by phnoel** [comment]
OK, thank you
Does this surprise you?
Have you ever been confronted with this problem?

**Comment by Globulopolis** [comment]
> Have you ever been confronted with this problem?

And yes and no.

**Comment by phnoel** [comment]
> > Have you ever been confronted with this problem?
> 
> And yes and no.

:)

**Comment by exstreme** [comment]
Hello!
I think, you don't find a free solution. 
I tried different ways to avoid problem with spam. By example, I used Recaptcha 3 and became high rate (about 80-90% that it was a human for spambots. And using cloud services helped filter this messages.

**Comment by exstreme** [comment]
If you have link in messages you can disable publish this messages, in another way I mean only cloud modules can help

**Comment by phnoel** [comment]
> If you have link in messages you can disable publish this messages, in another way I mean only cloud modules can help

That's what I do

> Hello! I think, you don't find a free solution. I tried different ways to avoid problem with spam. By example, I used Recaptcha 3 and became high rate (about 80-90% that it was a human for spambots. And using cloud services helped filter this messages.

What is "cloud service"?

**Comment by exstreme** [comment]
cleantalk by example
