### ISSUE TITLE
Комментарий не сохраняется в базе и нет ни каких ошибок

### ISSUE THREAD

**Issue by a0677703787** [exstreme/Jcomments-4#107]
Добрый день!
J4 локально на openserver установлен pkg_jcomments_4.0.22.zip
при любых вариантах настроек (с капчей и без / с правильной капчей и не правильной / с лимитом на длину сообщения и без него) при нажатии кнопки "отправить" над блоком на пару секунд появляется колесико, потом оно исчезает и все.
ни каких сообщений: ни об удачной или неудачной отправке, ни о неверной капче, ни сообщения что тема короткая.
как результат ни в списке админки, ни в базе ничего нет.
капча мне пока не нужна, жалко что без нее тоже не работает.
Подскажите плизз куда копать.

**Comment by Globulopolis** [comment]
Для начала посмотреть логи php. Затем включить логирование в самой Joomla и посмотреть логи там.
Если ничего не будет в логах то по F12 в браузере открыть консоль и там на вкладке Сеть есть лог запроса. Нажать кнопку Сохранить для комментария и посмотреть этот POST-запрос. В вкладке `Ответ` будет что-то написано, а также код ответа.

Примерно так это выглядит в firefox при успешной отправке комментария.
![image](https://user-images.githubusercontent.com/740757/183257405-a6481e52-f9b8-4068-814b-284df126412c.png)

**Comment by a0677703787** [comment]
Огромный респектище за оперативность и за подсказку где копнуть!!!
Все полечил благодаря подсказке из скрина.
у меня POST улетал на 301, лажа была в .htaccess
сбросил .htaccess по дефолту и "о чудо" коменты заработали
нужные редиректы потом настрою и перепроверю
