### ISSUE TITLE
Ошибка при  отключении юзера

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#108]
Заметил, если отключить юзера, то такая ошибка возникает:

An error has occurred.

    0 Argument 4 passed to PlgUserJComments::onUserAfterSave() must be of the type string, null given, called in /var/www/site.ru/www/libraries/src/Plugin/CMSPlugin.php on line 279 

Joomla 4.2.1 + последняя версия JC

**Comment by exstreme** [comment]
Привет, попробуешь https://github.com/exstreme/Jcomments-4/commit/628f48269123eca69c054f42425c85945e9a8f2f с этим коммитом?

**Comment by Sulpher** [comment]
Да, это помогло. спасибо
