### ISSUE TITLE
Invisible reCAPTCHA v3

### ISSUE THREAD

**Issue by jorgenqv** [exstreme/Jcomments-4#110]
Hello,
Any hope for getting Invisible reCAPTCHA to work? No I get "Empty solution not allowed" when submitting the frontend form in Jcomments 4.0.23 running Joomla 4.2.3 with Cassiopeia template.
Thanks.

**Comment by exstreme** [comment]
Hello!
Did you properly configure Recaptcha plugin? Is there only one recaptcha without any conflict?

**Comment by jorgenqv** [comment]
Yes, thank you so much for the super quick fix, works perfectly!
