### ISSUE TITLE
Ugly smiles error

### ISSUE THREAD

**Issue by aspergerway** [exstreme/Jcomments-4#117]
If you leave the option to post smiles, they all appear vertically instead of being hidden with a dropdown.

**Comment by Globulopolis** [comment]
Try to remove component(package) and install again. I cannot reproduce this bug(?).

If leave only smiles when they appears in horizontal line(not dropdown).

**Comment by exstreme** [comment]
Can you share URL, may be any conflict in frontend with another extension?

**Comment by aspergerway** [comment]
Done!
But the same thing happens:

https://www.pfuno.sviluppo.host/preghiere

**Comment by Globulopolis** [comment]
> Done! But the same thing happens:
> 
> https://www.pfuno.sviluppo.host/preghiere

This is no issue with component, but with your template.

![image](https://user-images.githubusercontent.com/740757/210497021-47cc83ff-eb88-4d19-8c37-efed8ad2653b.png)

Remove `display: block;` or change to `display: inline-block;`.

**Comment by exstreme** [comment]
I think,  we can add to #comments-form img.smile  property display:inline-block;

**Comment by aspergerway** [comment]
Many thanksat all!

**Comment by aspergerway** [comment]
> I think, we can add to #comments-form img.smile property display:inline-block;

What is the correct rigas of code? This one?

#comments-form-img.smile {
    display:inline-block;
}

**Comment by aspergerway** [comment]
Last question: I don't see an option to be notified by email if someone responds to my comment.

**Comment by Globulopolis** [comment]
> Last question: I don't see an option to be notified by email if someone responds to my comment.

![image](https://user-images.githubusercontent.com/740757/210615909-6b570ad2-9215-44b7-a2bd-53c96af10092.png)

**Comment by aspergerway** [comment]
I didn't mean to the administrator. I mean that if a user writes, they can choose whether or not to receive an email if someone responds to the comment without having to constantly check the page.

**Comment by Globulopolis** [comment]
> I didn't mean to the administrator. I mean that if a user writes, they can choose whether or not to receive an email if someone responds to the comment without having to constantly check the page.

User can subscribe to thread.

**Comment by aspergerway** [comment]
Public and guest as well?

**Comment by Globulopolis** [comment]
> Public and guest as well?

Guests can subscribe too. Just allow checkbox in access rules under component settings.

**Comment by aspergerway** [comment]
Ok, thanks!

**Comment by aspergerway** [comment]
Many thanks!

Will import/export from toward jcomment be possible from !JExtensionstore, already fork of jcomments?

**Comment by Globulopolis** [comment]
> Will import/export from toward jcomment be possible from !JExtensionstore, already fork of jcomments?

I do not know this.
