### ISSUE TITLE
Column mixed in Subscriptions table

### ISSUE THREAD

**Issue by vicioussn** [exstreme/Jcomments-4#118]
Hello!

When subscription is created, email comes to `name` column and name - to `email`.

**Comment by Globulopolis** [comment]
In backend or frontend?

**Comment by vicioussn** [comment]
It's in the MySQL table:

"id","object_id","object_group","lang","userid","name","email","hash","published","source","checked_out","checked_out_time"
"672","231","com_content","en-GB","0","ttttt@gmail.com","test1","f211cbd30febda2981e2a326f7a679cb","1",,"0",NULL

**Comment by Globulopolis** [comment]
@vicioussn look like something wrong with you subscription table. Go to `administrator/index.php?option=com_installer&view=database` and check for errors.
