### ISSUE TITLE
access = 0 for custom component objects

### ISSUE THREAD

**Issue by iantrudell** [exstreme/Jcomments-4#119]
I'm trying to convert my custom Joomla component plugin to work with the Joomla 4 version of JComments, but when I rebuild the #__jcomments_objects table, the "access" column is always 0 for every row related to the custom component, while the com_content and other default components show access = 1.

How do I make it so that newly submitted comments on my custom component's pages have access = 1 in the #__jcomments_objects table? I do not see anywhere in the Admin Control Panel to set the ACL for custom components/plugins like I could per-language in the Joomla 3 version.

**Comment by Globulopolis** [comment]
`access` field isn't related to ACL. It's a group access(Public, Registered, Guest, etc.).
This field going from jcomments plugins `components\com_jcomments\plugins\`. And another place where the field could be set is JCommentsObject::storeObjectInfo() helper and class JCommentsObjectInfo in classes folder. At least I have tested this piece of code with community builder component and this field = 0 too. But I can see the comment in user profile.

I'm not sure for 100% but you can try to set up the default value of this field in https://github.com/exstreme/Jcomments-4/blob/master/component/site/classes/objectinfo.php#L43 From null to 1.

**Comment by iantrudell** [comment]
> `access` field isn't related to ACL. It's a group access(Public, Registered, Guest, etc.). This field going from jcomments plugins `components\com_jcomments\plugins\`. And another place where the field could be set is JCommentsObject::storeObjectInfo() helper and class JCommentsObjectInfo in classes folder. At least I have tested this piece of code with community builder component and this field = 0 too. But I can see the comment in user profile.
> 
> I'm not sure for 100% but you can try to set up the default value of this field in https://github.com/exstreme/Jcomments-4/blob/master/component/site/classes/objectinfo.php#L43 From null to 1.

Setting the value for access to 1 seemed to work in the plugin, but now I'm getting an issue where new comments are duplicated 7 times in the backend, and 7 times in the mod_comments_latest module:

![duplicate_comments](https://user-images.githubusercontent.com/33202657/210394781-bd9f4289-b05c-4697-99a5-1d2764cde61b.PNG)

However, in the database "#__jcomments" table they are only listed once:
![jcomments_database_table](https://user-images.githubusercontent.com/33202657/210395284-f9aa6a06-4369-49a0-aa14-6027e755dc9c.PNG)

But in the database table "__jcomments_objects" there are 7 rows, one for each language:
![jcomments_database_table_objects](https://user-images.githubusercontent.com/33202657/210395901-533eb588-1ac7-4fbe-9562-17d192be8210.PNG)

How do I make sure that in the backend ACP's comments list, and in the frontend mod_comments_latest module, that it only displays once instead of many times?

**Comment by exstreme** [comment]
Hello! You should clear incorrect values manually
