### ISSUE TITLE
Problem Jcomments after Joomla 4 migration

### ISSUE THREAD

**Issue by philevr** [exstreme/Jcomments-4#120]
Hello,
I just achieved Joomla 4 local migration (Wampserver 3.2.5) which worked after multiple tries. I had Jcomments on Joomla 3.10 that I have desinstalled before migration keeping all specific tables.
I installed Jcomments for Joomla 4 (pkg_jcomments_4.0.25.zip) after migration : 
- No problem with Jcomments administration and I put again all my Jcomments parameters and custom BBcode in the backend
- Fatal error on the frontend : each page with comment cannot be accessed with display of the following message
                 _**0 - JComments::makeSeed(): Return value must be of type int, float returned**_

I don't know what is the cause of this error and what to do to correct it !
Could you  help me ? Thanks.

**Comment by Globulopolis** [comment]
Very strange. This issue allready fixed in 4.0.25.
What PHP version you are using on the server?

**Comment by philevr** [comment]
PHP 8.0.10

**Comment by philevr** [comment]
Same problem with PHP 7.4.9

**Comment by exstreme** [comment]
Hello!
Turn on debug please and share full stack trace of error.

**Comment by philevr** [comment]
Full stack trace attached in jpeg file.

![Jcomments-error-J4](https://user-images.githubusercontent.com/7049368/211042849-966868ef-e7da-41f7-b0d7-4ddf3ead07c1.jpg)

**Comment by Globulopolis** [comment]
@philevr can you test this file https://github.com/exstreme/Jcomments-4/blob/acd1eb1800625af47caec109a8de6dff806d1133/component/site/jcomments.php ? Just replace.

**Comment by Globulopolis** [comment]
@philevr нou need to re-configure the component and access rights.

**Comment by philevr** [comment]
What does that mean ? I am not very familiar with Joomla developments  and related procedures...
Thanks for your help and your work about Jcomments !! It's a component I have been using since Joomla 1.5, free and very efficient !

**Comment by Globulopolis** [comment]
> What does that mean ?

Go to `administrator/index.php?option=com_config&view=component&component=com_jcomments` and set up as you need.

**Comment by philevr** [comment]
OK, the place where Jcomments settings are. I have already reported all parameters from my joomla  version (Jcomments 3.0.7.9).
Is there anything else to do ?

**Comment by Globulopolis** [comment]
@philevr parameters from 3.0 and 4.0 is not the same.

**Comment by philevr** [comment]
I was not aware of that and I'll have a look at new Jcomments settings.
Is there a specfic documentation about those differencies between 3.0 and 4.0 ?

**Comment by exstreme** [comment]
No(

**Comment by Globulopolis** [comment]
> I was not aware of that and I'll have a look at new Jcomments settings. Is there a specfic documentation about those differencies between 3.0 and 4.0 ?

The main difference between 3.0 and 4.0 in the access rules. In jcomments 4.0 the matrix rules is standard matrix rule for Joomla 3 and Joomla 4, see https://magazine.joomla.org/all-issues/january-2022/joomla-4-for-clients-managing-users-access
Access rules in jcomments 4 not backward compatible. You need reconfigure permissions.

![image](https://user-images.githubusercontent.com/740757/211148850-490140fc-bca6-423a-b9c4-e6d108c77cac.png)
