### ISSUE TITLE
add hCaptcha (captcha for people with disabilities)

### ISSUE THREAD

**Issue by aspergerway** [exstreme/Jcomments-4#122]
It would be useful to add hCaptcha.

Also because there may be users with accessibility needs, and hCaptcha allows users with disabilities to register so that hcaptcha gives nothing to resolve (which users would not be able to) and see the cookie giving authentication silently.

------

Sorry, where can requests be posted?

**Comment by Globulopolis** [comment]
hCaptcha support already added in https://github.com/exstreme/Jcomments-4/commit/f18b877928a435ad05600b2cb0c11b6d136142b3

**Comment by aspergerway** [comment]
I don't understand. Now if I look in the options I only see kcaptcha.
Opening the link you posted, I see that in the code there is also hCaptcha.
Does that mean I need to edit or replace some files?

Sorry but this is my first time interfacing on github!

**Comment by Globulopolis** [comment]
> I don't understand. Now if I look in the options I only see kcaptcha.
> Opening the link you posted, I see that in the code there is also hCaptcha.
> Does that mean I need to edit or replace some files?
> 
> Sorry but this is my first time interfacing on github!
> 
> 

You need to install hCaptcha plugin. We not developing this plugin.

**Comment by aspergerway** [comment]
I got it, just install and configure this:
https://data2site.com/download/hcaptcha
and hcaptcha appears trans the captcha options in the security options.
