### ISSUE TITLE
Line break not working in Jcomments 4.0.27

### ISSUE THREAD

**Issue by philevr** [exstreme/Jcomments-4#126]
I come back with my problem of line break with the last version of Jcomments (4.0.27).

Previously, you asked me to access my site : not possible because my migrated site was only local (Wamp). I have now proceeded to Joomla 4 migration of my site to my external server with a version which is not in production.
You can access this site on https://corse-sauvage/CS-J4.

As an exemple of NEW comment processed with the new Jcomments, see the last comment on this page : https://corse-sauvage.com/CS-J4/randonnee/sud-est-corse/br%C3%A8che-du-carciara.html

If you register as visitor (on the home page with mega menu and mouse on "Accueil"), you will be able to edit and suppress a comment you sent by yourself !

**Comment by Globulopolis** [comment]
@philevr please download https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/jcomments.ajax.php and replace the file `components/com_jcomments/jcomments.ajax.php`.
Download https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/smilies.php and replace the file `components/com_jcomments/classes/smilies.php`

Edit test comment(insert some new lines) save and let me know the result.

**Comment by philevr** [comment]
Wonderful !
It works as you can see the same comment previously shown to you now corrected (file attached).

![Sans titre - 13](https://user-images.githubusercontent.com/7049368/212570548-e3da4621-d5cf-4d75-ad7e-97ddae84ce7b.jpg)

Was it a bug ?

Option : could you do something for the incorrect wiki "list" (already incorrect in Jcomments/J3) ?
In my comment, I write ligne 1 ligne 2 ligne 3 as a list : 
- Processing gives [list][*]ligne 1 
ligne 2
ligne 3[/list]
- Instead of [list][*]ligne 1
[*]ligne 2
[*]ligne 3[/list]

**Comment by Globulopolis** [comment]
> Was it a bug ?

Not really.

> Option : could you do something for the incorrect wiki "list" (already incorrect in Jcomments/J3) ?

Do you mean when entering the list elements one by one? If yes - no, I cannot fix it. Just copy/paste list elements.
