### ISSUE TITLE
RSS flow for last comments Jcomments 4

### ISSUE THREAD

**Issue by philevr** [exstreme/Jcomments-4#130]
With Jcomments 3, we could use an RSS adress for an XML file with the 100 last comments of the site : cf. [https://www.joomlatune.com/jcomments-faq.html](url)

> By default, the component exports the RSS-feed of comments for every item. The links to the RSS-feed can be found under the comments. However, it required sometimes to export the RSS-feed for all components of all items. Such RSS-feed is available under the following link: http://your_website_url/index2.php?option=com_jcomments&task=rss_full&no_html=1. There are 100 latest comments are displayed by default. This number can be changed in the future versions of the component.

URL  http://your_website_url/index2.php?option=com_jcomments&task=rss_full&no_html=1 no longer works with Jcomments 4.

Have you some information about this issue ?

**Comment by Globulopolis** [comment]
@philevr try this
Replace the file in `components/com_jcomments/views/comments/view.feed.php`
by this `https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/views/comments/view.feed.php`

**Comment by Globulopolis** [comment]
You can use:
to get comments for certain component by article ID - 
`index.php?option=com_jcomments&view=comments&task=rss&object_id=1&object_group=com_content&format=feed`
Where `object_id` is the article ID.

`index.php?option=com_jcomments&view=comments&task=rss_full&object_group=com_content&format=feed`
to get last comments for certain component

`index.php?option=com_jcomments&view=comments&task=rss_user&userid=1&format=feed`
to get comments for certain user

**Comment by philevr** [comment]
It's fine !
All the three comments URLs seem to work well... and the second one is what I was using...

**Comment by gafason1960** [comment]
The update is a success, you can install it in Joomla 4 without any difficulty from version 4.0.27, now my site has version 4.0.28 without any problem, thanks (exstreme)

**Comment by gafason1960** [comment]
A quick question: will you be able to develop JComments for Joomla 6? Thanks.
