### ISSUE TITLE
Плагин Система - Комментарии

### ISSUE THREAD

**Issue by radioacoustick** [exstreme/Jcomments-4#131]
Здравствуйте.
Комментарии не выводятся в место указанное тегом {jcomments}, а всегда в конце статьи. Обнаружил ошибку в плагине
[[https://github.com/exstreme/Jcomments-4/blob/master/plugins/content/jcomments.php](url)](https://github.com/exstreme/Jcomments-4/blob/ad2b0545da5e5d7381c6546a8b3aa0d421da032d/plugins/content/jcomments.php#L191)
На 191 строке идет сравнение параметра со строкой 'prepareContent'. На самом деле параметр в настройках плагина (jcomments.xml - строка 90) определен иначе - 'onContentBeforeDisplay' и условие сравнения поэтому всегда отдает false.
Нужно чтобы имена совпадали. Я предлагаю исправить 191 строку на:
`if ($this->params->get('show_comments_event') == 'onContentBeforeDisplay')`

**Comment by Globulopolis** [comment]
Спасибо! Поправил ;)
