### ISSUE TITLE
Не сохраняются настройки 

### ISSUE THREAD

**Issue by DoctorDeatch** [exstreme/Jcomments-4#134]
Приветсвую 
 настройки пагина не сохраняются 
пытаещеся выделить несколько категорий -  на странице настроек плагина также остаются гореть Все 
тоже касается всехнастроек
таблици с настроуками _jcomments_settingsв этой версии не появляется, но возможно так и задуманно

**Comment by Globulopolis** [comment]
Настройки какого плагина? В плагинах нет выбора категорий, они есть в настройках самого компонента.
Как вы устанавливали компонент? Обновляли или на чистую ставили?

**Comment by DoctorDeatch** [comment]
странно , из настроек самого компонента не сохраняет компонент-jcoments-настройки 
а если входишь по ссылки  administrator/index.php?option=com_config&view=component&component=com_jcomments
то там все настаивается и сохраняется

**Comment by Globulopolis** [comment]
Как вы устанавливали компонент? Обновляли или на чистую ставили?

**Comment by Globulopolis** [comment]
Хм... Может в логах php есть какие-то ошибки?
А в общем рекомендую использовать `administrator/index.php?option=com_config&view=component&component=com_jcomments` вместо настроек в самом компоненте, т.к. в дальнейшем они будут убраны из компонента.

**Comment by DoctorDeatch** [comment]
коробе глюку похоже связан с .htaccess

**Comment by DoctorDeatch** [comment]
4,0,27
