### ISSUE TITLE
Вывод определенного количества комментариев

### ISSUE THREAD

**Issue by Alexlip531** [exstreme/Jcomments-4#135]
Подскажите, а как можно вывести к примеру 5 комментариев под постом?

**Comment by Globulopolis** [comment]
Никак. Если выбрать Плоский список, то кол-во комментариев на страницу только есть. Настройка глобальная для всех материалов.

**Comment by Alexlip531** [comment]
> Никак. Если выбрать Плоский список, то кол-во комментариев на страницу только есть. Настройка глобальная для всех материалов.

Спасибо! Точно "Плоский список" а я думаю где настройка. Там то можно указать количество. Это в Древовидном нельзя.
