### ISSUE TITLE
JDownloads integration file uses out of date identifier "file_id"

### ISSUE THREAD

**Issue by Rajada** [exstreme/Jcomments-4#136]
File components/com_jcomments/plugins/com_jdownloads.plugin.php uses an identifier "file_id" in lines 19 and 21 that was changed to just "id" as of JDownloads 3.2. There may be other out of date identifiers as well.

**Comment by Rajada** [comment]
I fixed this issue on my own site by changing the offending query on lines 1-21 to:

```
$query = "SELECT id as id, title as title, submitted_by as owner, catid"
. " FROM #__jdownloads_files"
. " WHERE id = " . $id;
```

**Comment by Globulopolis** [comment]
Tanks for report a problem. I need some test on J4 and jDownloads 4 beta.

**Comment by Rajada** [comment]
I have just been made aware that the author of JDownloads has made an updated version of this plugin file at https://www.jdownloads.com/index.php/downloads/download/22-special-extensions-jd4-0/72-jcomments-plugin-for-jd-4-0.html
