### ISSUE TITLE
[plg_jcomments_avatar] JomSocial profile link + profile photo

### ISSUE THREAD

**Issue by universewrld** [exstreme/Jcomments-4#138]
Will there be support for displaying a profile picture from the JomSocial component and a link to the user's profile from the JomSocial component?

The Joomla 3 version of this plugin had integration with JomSocial.

**Comment by Globulopolis** [comment]
@universewrld please test it https://github.com/Globulopolis/Jcomments-4/raw/master/build/plugins/plg_jcomments_avatar_4.2.6.zip

**Comment by Globulopolis** [comment]
> > @universewrld please test it https://github.com/Globulopolis/Jcomments-4/raw/master/build/plugins/plg_jcomments_avatar_4.2.6.zip
> 
> it works!
> 
> only the SEF router does not work.
> 
> for example, the link looks like: `/component/community/admin/profile`
> and should look like: `/community/admin/profile`

I cannot test it because I do not have a jomsocial component. The profile link uses a joomla router, not from jomsocial.
