### ISSUE TITLE
Hide comment form breaks some JS

### ISSUE THREAD

**Issue by Giuse69** [exstreme/Jcomments-4#140]
Hi, if the comment form is set to Hide, some javascripts get broken, infact there is no emoticon, submission throws error and so on. Maybe there is a conflict with the JS that opens the form when click on "Leave a comment" button?
JComments 4.0.27 and Joomla 4.3.2 with cache and JCH plugin disabled.
thanks

Giuse

**Comment by Globulopolis** [comment]
@Giuse69 please test. Download this file https://github.com/Globulopolis/Jcomments-4/blob/master/component/site/layouts/comment-form.php and replace the file in `components/com_jcomments/layouts/` folder.

**Comment by Giuse69** [comment]
yes, it works! You're so fast! Thanks
