### ISSUE TITLE
unable to install 4.0.28

### ISSUE THREAD

**Issue by Giuse69** [exstreme/Jcomments-4#148]
trying to install latest 4.0.28 fails for "Unable to detect manifest file"

**Comment by Globulopolis** [comment]
Very strange. Are you trying to install via "Upload Package File" or "Extensions: Update" panel or "Install from Web"?
I have found an issue only for third method https://github.com/joomla/joomla-cms/issues/39823

If the first and second methods throws this error try to reinstall jcomments package.

How to reinstall:
1. Make backup.
2. Go to `administrator/index.php?option=com_jcomments&view=settings` and click on `Export` button to save settings
3. Go to administrator/index.php?option=com_installer&view=manage and find `JComments package`
4. Tick checkbox and click on `Uninstall` button. Comments database will not be deleted.
5. Go to administrator/index.php?option=com_installer&view=install on `Upload Package File` tab. Upload new package.

**Comment by dron-baton** [comment]
Same problem. Uninstalled package 4.0.28, trying to install 4.0.28 - Error: 
The installation path does not exist.
Package: Installation: An error occurred during installation: com_jcomments.zip.
Danger
Package installation error.

**Comment by Globulopolis** [comment]
@dron-baton можете привести информацию из administrator/index.php?option=com_admin&view=sysinfo ?

**Comment by dron-baton** [comment]
Без проблем: https://satworld.ru/systeminfo.txt

**Comment by Globulopolis** [comment]
> Думаете проблема в PHP 8.2?

Предыдущая версия https://github.com/exstreme/Jcomments-4/releases/download/v4.0.27/pkg_jcomments_4.0.27.zip ставится или такая же ошибка?

**Comment by dron-baton** [comment]
Без проблем установилась:
success
Установка пакета успешно завершена.
JComments lets your users comment on content items

**Comment by DoctorDeatch** [comment]
аналогично
стоит версия  4.0.27 
при попытки обновить до версии  до 4.0.28 : Пути установки не существует.

**Comment by Globulopolis** [comment]
Пробуйте перекачать https://github.com/exstreme/Jcomments-4/releases/download/v4.0.28/pkg_jcomments_4.0.28.zip и установить.

**Comment by Giuse69** [comment]
I tried this new version with "upload & install joomla extension" and now it installs correctly (before it didn't)
thanks

**Comment by DoctorDeatch** [comment]
Спасибо, так сработало

**Comment by dron-baton** [comment]
> Пробуйте перекачать https://github.com/exstreme/Jcomments-4/releases/download/v4.0.28/pkg_jcomments_4.0.28.zip и установить.

Подтверждаю! С этим архивом установка прошла без проблем. Все комментарии сохранились.
Спасибо за оперативную поддержку!
