### ISSUE TITLE
Trouble upgrading Jcomments 4.0.27 to 4.0.28

### ISSUE THREAD

**Issue by jorgenqv** [exstreme/Jcomments-4#149]
Unfortunately I can not upgrade Jcomments in backend in Joomla 4.3.4 by going to System, Update, Extensions.
 
Error: The checksum verification failed. Please make sure you are using the correct update server!

See System Information exported as txt and screen dump . 
What to do?

Thanks!

[systeminfo-2023-09-20T17 19 51+00 00.txt](https://github.com/exstreme/Jcomments-4/files/12675896/systeminfo-2023-09-20T17.19.51%2B00.00.txt)

![Extension_update_J434_ 2023-09-20 19-15-23](https://github.com/exstreme/Jcomments-4/assets/5297223/85f7f5ce-954e-49d5-aeb0-dce55adae4ca)

**Comment by Globulopolis** [comment]
Fixed via https://github.com/exstreme/Jcomments-4/commit/03ae16d45a924c40fa2cccbd17e702a94c809372
Try to update again.

**Comment by jorgenqv** [comment]
Wow that was quick, and yes, worked like a charm. Thank you!

**Comment by jorgenqv** [comment]
Closing
