### ISSUE TITLE
error to display comments

### ISSUE THREAD

**Issue by nickg001** [exstreme/Jcomments-4#15]
Hello
I am on joomla 4.0.4 and I updated jcomment to com_jcomments_v4.0.2
But on get an error :
0 Class 'JString' not found
when want to display my comments
Thanks for your help

**Comment by Globulopolis** [comment]
`JString` is deprecated and renamed to `StringHelper` in all files in jcomments.
Check for file `classmap.php` in `library` folder. If you have no this file in this folder, when unpack that file from Joomla distributive.

**Comment by exstreme** [comment]
Hello, turn on debug and tell, where was an error occurred

**Comment by nickg001** [comment]
hello , I have classmap.php in library folder.
there is debug infos :

![githuhcomments](https://user-images.githubusercontent.com/39922087/139526114-51b262a3-22fc-44fb-baa8-985c84fa23c3.png)

https://www.oman-voyage.com/en/testimonials

**Comment by exstreme** [comment]
Disable mod_jcomments_latest, we don't support him.
May be in the future can be adapted.

**Comment by nickg001** [comment]
I Disabled mod_jcomments_latest
ok it works now
Thanks you so much
