### ISSUE TITLE
Moving the Jcomment button on blog view

### ISSUE THREAD

**Issue by Dano7762** [exstreme/Jcomments-4#152]
Hello,
I would like to know how to move the button to add a comment (or read comments) under the introduction text. By default it's on top, but I'd like to move it below the introduction text.
What file do I need to modify?

Thanks for your help

**Comment by Globulopolis** [comment]
Search for `Content - Comments (JComments)` plugin. Option `Links Position` should help.

**Comment by Dano7762** [comment]
Thank you very much !
