### ISSUE TITLE
Jcomments usage in Flexicontent

### ISSUE THREAD

**Issue by tramber91** [exstreme/Jcomments-4#154]
Hi all
thanks for the Fork.

I test your latest version of Jcomments integrated with latest version of Flexicontent (FC) in Joomla 4.4.0 website.
Was ok with JComments 3.0.7

In J4,  i have a fatal error : 0 Call to undefined method JComments::showComments()

due to one of the Flexicontent line dedicated to show jcomments comments.

`echo JComments::showComments($item->id, 'com_flexicontent', $this->escape($item->title));`

FC support need to see if the JComments::showComments method still exists on the jcomments 4.0.28 side ?

i don't know if it is a jcomments issue. Will see if i can continue to use jcomments in Flexicontent 

thanks for your support

**Comment by Globulopolis** [comment]
Hi!
This is not related to com_jcomments.
I have tested the latest versions of Joomla 4 and components and see some errors in FC. There are no global changes in the com_jcomments content plugin. For example, the missing property `readmore` of the article object, which leads to an error loading the `readmore` layout. The absence of the text of the article when displaying comments
 I recommend contacting the FC developers in their Github repo.

**Comment by tramber91** [comment]
Hi for info,
first modif done in FC (see with FC)

FC use today code below to display Jcomments
`JComments::showComments`

It is OK for J3 but need to be
`JComments::show`
for Joomla 4

find with a reading of Eventbooking jcomments plugin

```
if (EventbookingHelper::isJoomla4())
		{
			echo JComments::show($row->id, 'com_eventbooking', $row->title);
		}
		else
		{
			echo JComments::showComments($row->id, 'com_eventbooking', $row->title);
		}
```

OK now - Jcomments 4 comments are displayed via FC in Joomla 4 with one line modification.

Current issue is now a JS issue with usage of the FC gallery fields. another story.
