### ISSUE TITLE
Не отправляются сообщения о появлении комментария и не появляется сообщение

### ISSUE THREAD

**Issue by kureshtar** [exstreme/Jcomments-4#156]
Добрый день.
Joomla 4.4.1 , Jcomments 4.0.28
При отправке комментария на фронте не выходит сообщение об успешной отправке комментария и на почту не приходят письма о появлении комментария, хотя в базе комментарий сохраняется.
Пробовал на php 7.4, 8.0 и 8.1 - результат тот же.
До обновления Joomla все работало.
Заранее спасибо.

**Comment by exstreme** [comment]
Привет!
А с почтовыми сообщениями нет проблем на сервере? Тестовое письмо из админки успешно доходит?

**Comment by Globulopolis** [comment]
До обновления какая версия Joomla стояла?

**Comment by kureshtar** [comment]
Спасибо за реакцию.
До обновления стояла Joomla 4.1.2, давно не обновлялся.
С почтовым сервером проблем нет, после ручной публикации комментариев уведомления о публикации уходят на почту норм.

**Comment by Globulopolis** [comment]
В логах php есть какие-то ошибки после отправки комментария?
Если ошибок нет, попробуйте способ ниже.

Перед отправкой комментария, нажмите F12(консоль разработчика), перейдите на вкладку Сеть. Отправьте комментарий. В вкладке Сеть нажмите на строку с запросом типа POST. Справа вылезет информация, там нажмите вкладку Ответ. Что там в ней написано?

**Comment by kureshtar** [comment]
Добрый вечер.
Высылаю содержимое вкладки Ответ из Консоли браузера по F12:
Судя по ответу не нравится строка 39 в файле \plugins\jcomments\autosubscribe\autosubscribe.php

 $owner = JCommentsObjectHelper::getOwner($comment->object_id, $comment->object_group);


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru" dir="ltr">
<head>
	<title>0 - Ошибка: 0</title>
	<link rel="stylesheet" href="/templates/template/css/styles.css" type="text/css" />
</head>

<body id="error">
	<div class="center">

		<h1 class="error">
			<span>0</span>
		</h1>
		<h2 class="title">Class 'JCommentsObjectHelper' not found</h2>
        
		<p class="message">The Page you are looking for doesn't exist or an other error occurred. <a href="javascript:history.go(-1)">Go back</a>, or head over to <a href="/">Главная страница</a> to choose a new direction.</p>
        		
                <p><strong>Вы не можете посетить страницу по одной из причин:</strong></p>
				<ol>
					<li>Устаревшая закладка/избранное</li>
					<li>Кэш поисковой системы ссылается на устаревшую страницу сайта</li>
					<li>Некорректный адрес страницы сайта</li>
					<li>Вам не разрешен доступ к странице сайта</li>
					<li>Запрашиваемый ресурс не найден</li>
					<li>При обработке запроса произошла ошибка.</li>
				</ol>

			<p>
				<table class="table table-striped table-bordered">
    <tr>
        <td colspan="3">
            <strong>Call stack</strong>
        </td>
    </tr>

    <tr>
        <td>
            <strong>#</strong>
        </td>
        <td>
            <strong>Function</strong>
        </td>
        <td>
            <strong>Location</strong>
        </td>
    </tr>

        <tr>
        <td>
            1        </td>

                <td>
            ()        </td>
        
                <td>
            JROOT\plugins\jcomments\autosubscribe\autosubscribe.php:39        </td>
            </tr>
        <tr>
        <td>
            2        </td>

                <td>
            plgJCommentsAutoSubscribe->onJCommentsCommentAfterAdd()        </td>
        
                <td>
            JROOT\libraries\src\Plugin\CMSPlugin.php:289        </td>
            </tr>
        <tr>
        <td>
            3        </td>

                <td>
            Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()        </td>
        
                <td>
            JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486        </td>
            </tr>
        <tr>
        <td>
            4        </td>

                <td>
            Joomla\Event\Dispatcher->dispatch()        </td>
        
                <td>
            JROOT\libraries\src\Application\EventAware.php:111        </td>
            </tr>
        <tr>
        <td>
            5        </td>

                <td>
            Joomla\CMS\Application\WebApplication->triggerEvent()        </td>
        
                <td>
            JROOT\components\com_jcomments\helpers\event.php:53        </td>
            </tr>
        <tr>
        <td>
            6        </td>

                <td>
            JCommentsEvent::trigger()        </td>
        
                <td>
            JROOT\components\com_jcomments\jcomments.ajax.php:606        </td>
            </tr>
        <tr>
        <td>
            7        </td>

                <td>
            JCommentsAJAX::addComment()        </td>
        
                <td>
            JROOT\components\com_jcomments\libraries\joomlatune\ajax.php:200        </td>
            </tr>
        <tr>
        <td>
            8        </td>

                <td>
            JoomlaTuneAjax->_callFunction()        </td>
        
                <td>
            JROOT\components\com_jcomments\libraries\joomlatune\ajax.php:216        </td>
            </tr>
        <tr>
        <td>
            9        </td>

                <td>
            JoomlaTuneAjax->processRequests()        </td>
        
                <td>
            JROOT\components\com_jcomments\jcomments.php:184        </td>
            </tr>
        <tr>
        <td>
            10        </td>

                <td>
            require_once()        </td>
        
                <td>
            JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71        </td>
            </tr>
        <tr>
        <td>
            11        </td>

                <td>
            Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()        </td>
        
                <td>
            JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73        </td>
            </tr>
        <tr>
        <td>
            12        </td>

                <td>
            Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()        </td>
        
                <td>
            JROOT\libraries\src\Component\ComponentHelper.php:361        </td>
            </tr>
        <tr>
        <td>
            13        </td>

                <td>
            Joomla\CMS\Component\ComponentHelper::renderComponent()        </td>
        
                <td>
            JROOT\libraries\src\Application\SiteApplication.php:208        </td>
            </tr>
        <tr>
        <td>
            14        </td>

                <td>
            Joomla\CMS\Application\SiteApplication->dispatch()        </td>
        
                <td>
            JROOT\libraries\src\Application\SiteApplication.php:249        </td>
            </tr>
        <tr>
        <td>
            15        </td>

                <td>
            Joomla\CMS\Application\SiteApplication->doExecute()        </td>
        
                <td>
            JROOT\libraries\src\Application\CMSApplication.php:293        </td>
            </tr>
        <tr>
        <td>
            16        </td>

                <td>
            Joomla\CMS\Application\CMSApplication->execute()        </td>
        
                <td>
            JROOT\includes\app.php:61        </td>
            </tr>
        <tr>
        <td>
            17        </td>

                <td>
            require_once()        </td>
        
                <td>
            JROOT\index.php:32        </td>
            </tr>
    </table>
			</p>

	</div>

</body>
</html>

**Comment by kureshtar** [comment]
[error.zip](https://github.com/exstreme/Jcomments-4/files/13876381/error.zip)
Сохранил в виде файла ответ от сервера для удобства просмотра (во вложении).
Заранее спасибо.

**Comment by kureshtar** [comment]
С отключенным плагином "JComments - AutoSubscribe" комментарии стали отправляться норм.
Спасибо большое.
Просто это плагин очень полезен тем, что автоматически подписывает авторов статей на комментарии к их статьям.
Я знаю вы этот плагин не обновляли.
Можно ли как-то этот функционал и в J4 допилить?
Чтобы автоматически авторов подписывать на комментарии к их статьям?
Или хотя-бы подскажите где в каком месте исправить код плагина на какой код, чтобы плагин заработал на J4?
Заранее спасибо.

**Comment by Globulopolis** [comment]
Мне нужно пару дней чтобы обновить плагин.

**Comment by Globulopolis** [comment]
Пробуйте https://github.com/exstreme/Jcomments-4/releases/tag/v4.0.29
Отпишитесь о результатах.

**Comment by kureshtar** [comment]
Большое спасибо!
Обязательно отпишусь...

**Comment by kureshtar** [comment]
Добрый вечер.
Обновил плагин.
Пока все по прежнему, но ошибка другая уже (во вложении).
[error.zip](https://github.com/exstreme/Jcomments-4/files/13928521/error.zip)

**Comment by Globulopolis** [comment]
> Добрый вечер.
> Обновил плагин.
> Пока все по прежнему, но ошибка другая уже (во вложении).
> [error.zip](https://github.com/exstreme/Jcomments-4/files/13928521/error.zip)
> 

Обновите компонент до 4.0.29

**Comment by kureshtar** [comment]
Не могу понять почему после обновления компонента с 4.0.28 до 4.0.29 перестают отображаться все комменты и форма, хотя настройки я смотрю все сохранились после обновления.
Я даже на всякий случай перед обновлением экспортировал настройки в файл, а затем после обновления импортировал их, но все равно комментарии и форма вообще не отображаются на 4.0.29.

**Comment by exstreme** [comment]
Отключите плагин AutoSubscribe, в нем видимо ошибка

**Comment by kureshtar** [comment]
После отключения плагина AutoSubscribe комментарии и форма все равно не появляются.
Похоже что-то в 4.0.29 мешает.

**Comment by Globulopolis** [comment]
Доступна новая версия https://github.com/exstreme/Jcomments-4/releases/tag/v4.0.30

**Comment by kureshtar** [comment]
Работает отлично. Спасибо большое!
