### ISSUE TITLE
Problem with jcomments 4.0.29

### ISSUE THREAD

**Issue by philevr** [exstreme/Jcomments-4#157]
No comment displayed on my two Internet sites after updating jcomments at 4.0.29 release.

Comments are found with admin, but are not displayed on the front site...

After updating, is there anything to do that i have forgotten ?

**Comment by Slackervaara** [comment]
I have identical problems on two different sites live site  Joomla 4.4.2 and local site Joomla 5.02 they are not changed by changing template to Cassiopeia, but changing back to previous version of JComments.

**Comment by Globulopolis** [comment]
Please wait. This is a bug. New version on the way...

**Comment by Globulopolis** [comment]
A new version available https://github.com/exstreme/Jcomments-4/releases/tag/v4.0.30

**Comment by Slackervaara** [comment]
Many thanks! The new version works perfectly on Joomla 4.4.2

**Comment by Slackervaara** [comment]
Its works also with my local site Joomla 5.02

**Comment by philevr** [comment]
OK, you fixed correctly this bug.
All is working fine with 4.0.30 for my two Internet sites and their local copies with WampServer...
Thanks a lot !
