### ISSUE TITLE
При быстрой модерации из письма ошибка "You have not supplied a valid HTTP status code"

### ISSUE THREAD

**Issue by kureshtar** [exstreme/Jcomments-4#158]
Добрый вечер.
При переходе по ссылке быстрой модерации из письма "Опубликовать" или "Удалить" или "Снять с публикации" появляется ошибка (но при этом Публикация, Снятие с публикации ил Удаление отрабатывают норм):
You have not supplied a valid HTTP status code
Joomla 4.4.1, Jcomments 4.0.30 (на 4.0.28 та же ошибка была)
Во вложении ответ от сервера в режиме отладки.
[error2.zip](https://github.com/exstreme/Jcomments-4/files/13929296/error2.zip)
Заранее спасибо.

**Comment by Globulopolis** [comment]
@kureshtar замените у себя файл `components/com_jcomments/jcomments.php` этим файлом https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/jcomments.php

Отпишите помогло или нет.

**Comment by kureshtar** [comment]
Спасибо большое.
Теперь ошибки нет. Работает как надо.
