### ISSUE TITLE
hardcoded: "Before posting a comment you must accept our terms of use."

### ISSUE THREAD

**Issue by jojo12** [exstreme/Jcomments-4#160]
this term is hardcoded: "Before posting a comment you must accept our terms of use."
should be:
FORM_ACCEPT_TERMS_OF_USE

**Comment by Globulopolis** [comment]
> this term is hardcoded: "Before posting a comment you must accept our terms of use." should be: FORM_ACCEPT_TERMS_OF_USE

It's not. Go to `Messages` tab in component and search for field `Terms of use message` and remove text. After that the default FORM_ACCEPT_TERMS_OF_USE will be use.

**Comment by jojo12** [comment]
Sorry, you're right!
