### ISSUE TITLE
Joomla 3 -> Jooomla 5

### ISSUE THREAD

**Issue by phnoel** [exstreme/Jcomments-4#161]
Hello,
I'm migrating my site from J3 to J5
I have installed Jcomments v 4.0.30 and I have two problems:
- I don't receive email notifications when a new review is posted (the email is correctly filled in)
- on the frontend, only one review appears on the Notices page...
Do you have any solutions for these two problems?
Thanks for your feedback
Philippe from France

**Comment by Globulopolis** [comment]
I tested it again, I don't see any problems.
Did you configure component access rights again after the migration? I strongly recommend checking the component settings. Also check the php and joomla logs for errors.

**Comment by Globulopolis** [comment]
> Are there any other settings to be made?

No.
Please look at the logs.

**Comment by Globulopolis** [comment]
Test this.
Replace this file `components/com_jcomments/jcomments.php` with this https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/jcomments.php

**Comment by phnoel** [comment]
Yes, now it works fine. Thank you.
Now, how can I export comments from jcomments 3.0.7.9 under jommla 3.5 and import them into jcomments 4.0.30 under joomla 5?

**Comment by Globulopolis** [comment]
> Now, how can I export comments from jcomments 3.0.7.9 under jommla 3.5 and import them into jcomments 4.0.30 under joomla 5?
phpmyadmin or heidisql or sqlyog community edition. Just backup all tables with _jcomments in table name. Import to database where the Joomla 5 installed. BEWARE! Change table prefix after export or before import.

**Comment by phnoel** [comment]
I did this. The comments are visible in the Jcomments backend and published, but they don't appear in the frontend.

**Comment by Globulopolis** [comment]
Go to administrator/index.php?option=com_installer&view=database and check for errors.
The tables has been changed since 3.0.7.

**Comment by phnoel** [comment]
Sorry, but I don't know how to do that!
Is it in Joomla admin?

**Comment by Globulopolis** [comment]
> Is it in Joomla admin?

Yes.

**Comment by phnoel** [comment]
Sorry, but I don't know what to do!!...
Otherwise, I only copied the josac_jcomments table, should I have copied the other 11?

**Comment by Globulopolis** [comment]
> should I have copied the other 11?

Yes.

**Comment by phnoel** [comment]
Okay, I'll do that.
For import/export, are there any parameters to change from the standard ones in Phpmyadmin?

**Comment by Globulopolis** [comment]
> Okay, I'll do that. For import/export, are there any parameters to change from the standard ones in Phpmyadmin?

Go to administrator/index.php?option=com_config&view=component&component=com_jcomments and set up access rules again

**Comment by phnoel** [comment]
Sorry, but I don't know how or where to do that! In the joomla backend (which tab)? in files via filezilla? in sql tables?
I really need to know more. Thanks

**Comment by Globulopolis** [comment]
1. Copy the database tables to the new database using phpmyadmin
2. Go to System->Global configuration in Joomla admin. Select Jcomments at left and configure the component.
3. Go to System->Database in Joomla admin and check for errors. Do repair.

**Comment by phnoel** [comment]
Thank you for this detailed procedure.
I did that, but my comments still don't appear!

**Comment by Globulopolis** [comment]
> I did that, but my comments still don't appear!

Can you see comments in backend?
Maybe it's better to provide me an access to your site? At least to frontend and backend.

**Comment by phnoel** [comment]
Yes of course
ident ; Globulopolis
pw : Globulopolis
link backend : https://www.weblim.x10.mx/administrator/index.php
Link frontend : https://www.weblim.x10.mx/index.php/poster-un-avis?view=comments

**Comment by Globulopolis** [comment]
1. I see only 13 comments in backend. This is all comments?
2. Any comment linked with the component(e.g. com_content) and item(article) via id and group. I see that the comments are not linked to the article(s).
3. You need to move the articles from the old version to the new one. Then the comments will be displayed.

**Comment by phnoel** [comment]
"to move the articles from the old version to the new one"?
I've already copied the jcomments table from the old version to the new one

**Comment by Globulopolis** [comment]
> I've already copied the jcomments table from the old version to the new one

Articles! Not a comments.

**Comment by phnoel** [comment]
OK, but how to do this?

**Comment by Globulopolis** [comment]
> OK, but how to do this?

It's not an easy. Ask on the Joomla official forum how to upgrade from old Joomla to new.

**Comment by phnoel** [comment]
OK, thank you for your help
