### ISSUE TITLE
Update Developer's Guide (Plugins) for Joomla 4/Joomla 5

### ISSUE THREAD

**Issue by iantrudell** [exstreme/Jcomments-4#162]
The old JComments had this Developer's Guide page describing how to write a plugin for JComments: https://www.joomlatune.com/jcomments-developers-manual.html

I am struggling to get my custom plugins for JComments to work in Joomla 4 and Joomla 5.

Custom components are not showing up in the various modules (Latest Comments, Top Posters, etc.) and there are many duplicates in the Admin Panel. Also objects are not being built in the database even though the comments exist and display on pages of the custom Joomla components.

Can the Developer Guide be updated and added to the README?

**Comment by Globulopolis** [comment]
Hmmm... As I know, nothing has changed in the "API" in the current version of the component.

**Comment by Globulopolis** [comment]
Please see https://github.com/exstreme/Jcomments-4/blob/master/FOR_DEVELOPERS.md
