### ISSUE TITLE
jcomments position

### ISSUE THREAD

**Issue by phnoel** [exstreme/Jcomments-4#163]
Hello,
I'm using Jcomments 4.0.30 [January 2023] with jooml5.
I want to display the submit form in an article AT THE BEGINNING of this article. No matter where I insert the {jcomments on} code, it's always at the bottom.

How can I fix this?
Thanks

**Comment by Globulopolis** [comment]
You can't do that. The form is linked to a list of comments and cannot be displayed separately.
