### ISSUE TITLE
Duplicated "Readmore" block in Yootheme template

### ISSUE THREAD

**Issue by Globulopolis** [exstreme/Jcomments-4#165]
"Comments" link in the list of Featured Articles doesn't seem to work. I still got “read more” button in my homepage. And of course, I have two read more buttons. Any solution?

![Crop It 2024-4-20 at 10 13 54](https://github.com/exstreme/Jcomments-4/assets/159842854/347a7ad5-470b-4303-ba63-7cb7d259f7f2)
![Crop It 2024-4-20 at 10 14 19](https://github.com/exstreme/Jcomments-4/assets/159842854/84b5f9b3-ca51-4545-9a74-f76761a15c37)

_Originally posted by @Vigoleto in https://github.com/exstreme/Jcomments-4/issues/86#issuecomment-2067588019_

**Comment by Globulopolis** [comment]
Replace your files from this zip https://github.com/Globulopolis/Jcomments-4/raw/master/build/packages/plg_content_jcomments.zip When turn off Readmore in settings, turn on `I'm using Yootheme` option in plugin settings.
Let me know about results.

**Comment by Vigoleto** [comment]
Hello 😊
Thank you kindly for the update!
I did as you told me but unfortunately the things stays the same ☹


![Crop It 2024-5-4 at 4 58 55](https://github.com/exstreme/Jcomments-4/assets/159842854/929bd3e2-2219-4c0a-93a9-a0bfeb9457e0)
![Crop It 2024-5-4 at 4 59 12](https://github.com/exstreme/Jcomments-4/assets/159842854/8e1d5f69-72fa-4810-90d9-79c3c2d0f133)

**Comment by Globulopolis** [comment]
Turn off "Readmore" in article options or menu options or global options.

**Comment by Vigoleto** [comment]
Now it works flawlessly!
Thank you kindly  @Globulopolis for all your help and support 😊


![Crop It 2024-5-4 at 16 19 28](https://github.com/exstreme/Jcomments-4/assets/159842854/b0946cdb-f679-4652-a793-2539a6759460)
