### ISSUE TITLE
php 8.1 Undefined property: stdClass::$profileLinkTarget in tpl_comment.php on line 50

### ISSUE THREAD

**Issue by kureshtar** [exstreme/Jcomments-4#168]
Добрый день.
Jcomments v4.0.30, Joomla 4.4.4.
После перехода с php 7.4 на php 8.1 в логах стало писать вот такой warning:
"Undefined property: stdClass::$profileLinkTarget in /components/com_jcomments/tpl/default/tpl_comment.php on line 50"
Подобные ворнинги вроде лечатся оборачиванием в isset:
isset($comment->profileLinkTarget)
правда не знаю на сколько это правильное решение.
Заранее спасибо.

**Comment by exstreme** [comment]
@kureshtar А что в плагине Аватара выставлено для этого поля?

**Comment by Globulopolis** [comment]
@kureshtar попробуйте заменить ваш `jcomments.php` этим файлом https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/jcomments.php
Дайте знать про результат.

**Comment by kureshtar** [comment]
Спасибо.
Да, вы верно подметили.
В плагине аватара у меня свое кастомное поле выставлено для зарегистрированных Seblod пользователей. Данный ворнинг появляется в логфайле только на страницах с комментариями, которые оставили пользователи, зарегистрированные через Seblod (в комментарии проставляется ссылка и фото на их страницу seblod-профиля).
На страницах без комментариев или с комментариями, которые оставили незарегистрированные пользователи или пользователи Joomla, такого ворнинга нет.

Замена файла jcomments.php ничего не поменяла, ворнинг также появляется.

**Comment by Globulopolis** [comment]
@kureshtar скриньте скрин настроек плагина аватара.

**Comment by kureshtar** [comment]
Прикладываю скрин:
![image](https://github.com/exstreme/Jcomments-4/assets/52793935/9aa9fcf1-f974-46a3-8a29-b3b9f897c843)

**Comment by Globulopolis** [comment]
Откуда Seblod? В текущей версии плагина нет этого.

**Comment by kureshtar** [comment]
Верно.
Выше писал, что это свое кастомное поле выставлено.
Если это с ним проблема, тогда ок.
Спасибо.

**Comment by exstreme** [comment]
Расскажите, как добавляли кастомное поле, думаю стоит просто добавить поддержку Seblod в плагин

**Comment by kureshtar** [comment]
Добрый день.
Я не программист, поэтому у меня очень кастомное решение , оно не универсальное, т.к. там идет запрос к базе, в которой из-за специфики себлода названия полей и таблиц в себлоде для типов контента могут иметь абсолютно любые значения (какие задаст вебмастер).
