### ISSUE TITLE
impossible to add comment

### ISSUE THREAD

**Issue by nickg001** [exstreme/Jcomments-4#17]
Hello
I can not add any comments. When I submit the form, the form stay display that's all.
https://www.oman-voyage.com/en/testimonials
thanks for your help

**Comment by Globulopolis** [comment]
Yep, I known about it. Please be patient, I'm working hard on adaptation to new Joomla and it's required a lot of time.

**Comment by exstreme** [comment]
See settings -> permissions -> guests -> autopublish.
I think, your comments are unpublished, you need manually enable it

**Comment by Globulopolis** [comment]
> 
> 
> See settings -> permissions -> guests -> autopublish. I think, your comments are unpublished, you need manually enable it

No, it's an error in jcomments.ajax.php. Will fix ASAP

**Comment by exstreme** [comment]
Topicstarter used stable 4.0.2 version, this version don't have last changes, which break comments publishing
