### ISSUE TITLE
does JComments work without a b/c plugin in Joomla 5?

### ISSUE THREAD

**Issue by universewrld** [exstreme/Jcomments-4#171]
I searched for this component's page on JED and didn't see a page for this component there with information about whether this plugin works in Joomla 5 without the system backwards compatibility plugin enabled, so I'm asking this question here.

will your component work correctly if the backwards compatibility plugin in @Joomla 5 is disabled?

**Comment by Globulopolis** [comment]
This commit https://github.com/Globulopolis/Jcomments-4/commit/9a9b7a7ff079da5f785866d53b743a4f36e0997d should fix some issues and component must work w/o behavior-compat plugin.
