### ISSUE TITLE
it's easy to make Jcomments compatible to J!5 without compatibility plugin

### ISSUE THREAD

**Issue by jojo12** [exstreme/Jcomments-4#173]
I updated your 4.0.31. But it continues to need the compatibility plugin.
But it is indeed very simple to make it compatible:
the compat plugin shows the classes you have to replace and what you have to add.
if debug is on, the call stack shows you, where you have to change!

**Comment by Globulopolis** [comment]
Can you be more specific where the problem?

**Comment by jojo12** [comment]
It is not a problem as long as you have the compatibility plugin enabled! As a next step we have to replace e.g. JFactory with Factory and to add at near the top of the file e.g. use Joomla\CMS\Factory;
But there are a lot of J... classes which need that.

**Comment by jojo12** [comment]
at least in backend the following lines give errors:
JROOT/administrator/components/com_jcomments/views/smilies/tmpl/default.php:39
JROOT/administrator/components/com_jcomments/views/subscriptions/view.html.php:45 
JROOT/administrator/components/com_jcomments/views/custombbcodes/view.html.php:46 
JROOT/administrator/components/com_jcomments/views/custombbcodes/tmpl/default.php:61
JROOT/administrator/components/com_jcomments/views/about/view.html.php:49

**Comment by Globulopolis** [comment]
[pkg_jcomments_4.0.32_pre.zip](https://github.com/exstreme/Jcomments-4/files/15416716/pkg_jcomments_4.0.32_pre.zip)

Please test this version.

**Comment by jojo12** [comment]
Sorry, I am on the road now, later.
It's not for correcting you but for helping for a good extension! Thanks

**Comment by jojo12** [comment]
Installed and tested on the road. Did not find error without compat plugin. Thanks
