### ISSUE TITLE
0 Class "JCommentsPlugin" not found

### ISSUE THREAD

**Issue by Slackervaara** [exstreme/Jcomments-4#175]
I  just updated JComments from GitHub.
https://github.com/exstreme/Jcomments-4
I have Joomla 4.4.4 and PHP 8.1 But when I afterwards edited an article and saved it I got error message:

0 Class "JCommentsPlugin" not found

# Function Location
1 () JROOT/components/com_jcomments/plugins/com_content.plugin.php:21
2 include_once() JROOT/components/com_jcomments/helpers/object.php:103
3 JCommentsObject::_loadObjectInfo() JROOT/components/com_jcomments/helpers/object.php:244
4 JCommentsObject::storeObjectInfo() JROOT/plugins/content/jcomments/jcomments.php:385
5 PlgContentJcomments->onContentAfterSave() JROOT/libraries/src/Plugin/CMSPlugin.php:289
6 Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
7 Joomla\Event\Dispatcher->dispatch() JROOT/libraries/src/Application/EventAware.php:111
8 Joomla\CMS\Application\WebApplication->triggerEvent() JROOT/libraries/src/MVC/Model/AdminModel.php:1277
9 Joomla\CMS\MVC\Model\AdminModel->save() JROOT/administrator/components/com_content/src/Model/ArticleModel.php:779
10 Joomla\Component\Content\Administrator\Model\ArticleModel->save() JROOT/libraries/src/MVC/Controller/FormController.php:676
11 Joomla\CMS\MVC\Controller\FormController->save() JROOT/libraries/src/MVC/Controller/BaseController.php:693
12 Joomla\CMS\MVC\Controller\BaseController->execute() JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
13 Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() JROOT/libraries/src/Component/ComponentHelper.php:361
14 Joomla\CMS\Component\ComponentHelper::renderComponent() JROOT/libraries/src/Application/AdministratorApplication.php:143
15 Joomla\CMS\Application\AdministratorApplication->dispatch() JROOT/libraries/src/Application/AdministratorApplication.php:186
16 Joomla\CMS\Application\AdministratorApplication->doExecute() JROOT/libraries/src/Application/CMSApplication.php:293
17 Joomla\CMS\Application\CMSApplication->execute() JROOT/administrator/includes/app.php:61
18 require_once() JROOT/administrator/index.php:32

com_content.plugin.php:21 is: class jc_com_content extends JCommentsPlugin

**Comment by Globulopolis** [comment]
Please test this version 
[pkg_jcomments_4.0.32_pre.zip](https://github.com/exstreme/Jcomments-4/files/15418253/pkg_jcomments_4.0.32_pre.zip)

**Comment by Slackervaara** [comment]
Many thanks for very rapid response! It works perfectly no error.
