### ISSUE TITLE
Ошибки в последнем обновлении 4.0.32

### ISSUE THREAD

**Issue by dron-baton** [exstreme/Jcomments-4#181]
Добрый день!
В JComments 4.0, после обновления до версии 4.0.32, в урлах смайликов перед файлами картинок двойной сплеш - "//"

Вместо  - /media/com_jcomments/images/smilies//rolleyes.png
Файл - rolleyes.gif
Этих вообще нет:
/media/com_jcomments/images/smilies//lol.png
/media/com_jcomments/images/smilies//redface.png

**Comment by Globulopolis** [comment]
`lol` теперь `laugh`
`redface` теперь `blush`

**Comment by Globulopolis** [comment]
Вроде исправил https://github.com/exstreme/Jcomments-4/releases/tag/v4.0.33

**Comment by dron-baton** [comment]
> Вроде исправил https://github.com/exstreme/Jcomments-4/releases/tag/v4.0.33

Двойной слешь в коде так и остался...
![Скриншот 03-06-2024 225238](https://github.com/exstreme/Jcomments-4/assets/27349234/0e1387b7-5e13-456c-b8b6-94237dc9d02d)

**Comment by Globulopolis** [comment]
Нужно кеш браузера почистить.
