### ISSUE TITLE
Cloudflare Turnstile CAPTCHA alternative

### ISSUE THREAD

**Issue by jorgenqv** [exstreme/Jcomments-4#195]
Hello,
It would be wonderful if JComments could work with Cloudflare Turnstile anti-spam plugin for Joomla!
https://github.com/SharkyKZ/joomla-turnstile-plugin

Is it possible? Now I get "Please enter security code displayed in the image!" when submitting the frontend form in Jcomments 4.0.33 running Joomla 4.4.9 with Cassiopeia template.
 
Thank you.

**Comment by Globulopolis** [comment]
Please test.
Replace:
`components/com_jcomments/layouts/comment-form.php` 
from https://raw.githubusercontent.com/exstreme/Jcomments-4/refs/heads/master/component/site/layouts/comment-form.php

`components/com_jcomments/jcomments.php` 
from https://raw.githubusercontent.com/exstreme/Jcomments-4/refs/heads/master/component/site/jcomments.php

`components/com_jcomments/jcomments.ajax.php` 
from https://raw.githubusercontent.com/exstreme/Jcomments-4/refs/heads/master/component/site/jcomments.ajax.php

**Comment by jorgenqv** [comment]
Very cool and super fast, thank you very much! 
Happy to confirm that it works fine with no issues on my site running Joomla 4.4.9, PHP 8.1.30 LAMP.
Using client Firefox 131.0.3 64bit for Linux and Android mobile and Chromium 130.0.6723.58  64bit Linux.
