### ISSUE TITLE
Uninstalling component will cause an errors.

### ISSUE THREAD

**Issue by Globulopolis** [exstreme/Jcomments-4#20]
![Screenshot_2021-10-31 Extensions Manage - j4test - Administration](https://user-images.githubusercontent.com/740757/139558300-b8795334-1f3c-471b-a144-06f342af5d68.png)

**Comment by exstreme** [comment]
https://github.com/exstreme/Jcomments-4/commit/a9e4844ded43ee672066d1362829b1cc55a98170 fixed
