### ISSUE TITLE
Removing Jcomments leads to a crash of the site

### ISSUE THREAD

**Issue by exstreme** [exstreme/Jcomments-4#24]
Failed opening required '/components/com_jcomments/helpers/content.php'

Plugins are removed incorrectly

**Comment by Globulopolis** [comment]
All plugins removed by Joomla com_installer.

![image](https://user-images.githubusercontent.com/740757/140808640-23c3aa0a-ed22-4413-a232-a0494155d07c.png)

**Comment by exstreme** [comment]
![image](https://user-images.githubusercontent.com/18548890/140819137-ea72f121-f89f-4dd5-9b33-c51d88740535.png)

**Comment by Globulopolis** [comment]
Look at the extensions table. Do you see plg_system_jcomments in `name` field?

**Comment by Globulopolis** [comment]
And com_jcomments_v4.0.3.zip in repo have an outdated jcomments.xml

**Comment by exstreme** [comment]
Why outdated?

**Comment by exstreme** [comment]
> Look at the extensions table. Do you see plg_system_jcomments in `name` field?

of course
![image](https://user-images.githubusercontent.com/18548890/140970550-fc042a3b-eb6e-4cd0-a7be-f3059738b5aa.png)

I can manually uninstall this plugins, but I don't understand:
1) Why they don't removed when I selected with component
2) Is it good, after uninstalling component, crash site without it

**Comment by Globulopolis** [comment]
> Why outdated?

Because I have update this file in PR.

**Comment by Globulopolis** [comment]
> > Look at the extensions table. Do you see plg_system_jcomments in `name` field?
> 
> of course
> ![image](https://user-images.githubusercontent.com/18548890/140970550-fc042a3b-eb6e-4cd0-a7be-f3059738b5aa.png)
> 
> I can manually uninstall this plugins, but I don't understand:
> 1) Why they don't removed when I selected with component
> 2) Is it good, after uninstalling component, crash site without it

It is something wrong with you local copy. Please contact with me via https://xn--80aeqbhthr9b.com/en/support/contacts.html
