### ISSUE TITLE
error messages are not displayed

### ISSUE THREAD

**Issue by exstreme** [exstreme/Jcomments-4#25]
Errors and warnings

**Comment by Globulopolis** [comment]
Which? JComments suppress all errors. I have added some Log::add() in critical places.

**Comment by exstreme** [comment]
on frontend, when publish comment or send to moderator etc

**Comment by Globulopolis** [comment]
> 
> on frontend, when publish comment or send to moderator etc

Where is a lot of errors in code. I have fixed it.

**Comment by exstreme** [comment]
You need examples or it is still in development?

**Comment by Globulopolis** [comment]
> You need examples or it is still in development?

In devel, should fixed in next PR.
