### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by exstreme** [exstreme/Jcomments-4#27]
![image](https://user-images.githubusercontent.com/18548890/140818781-9ab4e054-0031-4ea9-9a69-8be192ec7bdd.png)

cannot reproduce this problem, need more information

**Comment by Globulopolis** [comment]
Cannot reproduce too but it's because utf8mb4 encoding and VARCHAR 255 and some not too old mysql/mariadb servers. We should limit varchar to 191 or change it to text(smalltext, mediumtext).

**Comment by Globulopolis** [comment]
More info in https://joomlaforum.ru/index.php?topic=357384
