### ISSUE TITLE
Can't make new posts

### ISSUE THREAD

**Issue by dangerx82** [exstreme/Jcomments-4#38]
Hello! Great job with this new component for Joomla 4! I made the migration of my blog the last month and i installed in it your new version of JComments. Actually joomla version is: 4.0.5 
I have configurated the component to function like the old one on the previous version of the blog made with Joomla! 3.9.x
The new component show the old posts properly and is perfectly integrated in the front end. Great!
The problem now is that when I try to insert a new post on an article, the system seems to accept it, but without giving a message or an error.
After the click on the submit button, the system reset the text message box and no post is added to the component. 
I've tried to follow the logic of the software with the development tool of the browser. It seems function properly but there's no effect instead. I can't find the error (if there's one) or where the problem is...
Need help please!

**Comment by Globulopolis** [comment]
@dangerx82 at first, make sure you give the proper permission for user to post comments. Manage access rules is different in new version.
At second, turn on logging in Joomla and try to reproduce the issue and look at the log. And don't forget to look at the php log.

**Comment by exstreme** [comment]
Any link?

**Comment by dangerx82** [comment]
Thank's for yours answers! First I need that the visitors can post comments also if not registered. I set the permissions for the Pubblic group to post comments and reply to other comments. 
With these settings, the form is shown properly and if the kaptcha is not filled the component show correctly the error message. But if all the fields are filled with the data after the submit no error or confirm message is shown but the comment is not added.  
I check the php log but no error about JComments was recorded. 
The blog is under migration and for this it was offline. Now it can be reached at sandbox.dangerx82.it

**Comment by dangerx82** [comment]
Now in the Joomla log I found that: ERROR... com_jcomments	Field 'object_params' doesn't have a default value

**Comment by exstreme** [comment]
![image](https://user-images.githubusercontent.com/18548890/147774461-80c14087-c85e-4521-ba5f-c474958c5b30.png)
Do you set autopublish for guests?
If not, all comments from guests must be published manually

**Comment by dangerx82** [comment]
Hi exstreme! I've tried to set the permissions as you shown in the image... but nothing is changed... also I prefer moderate the comments before publish them... A question: the component need the creation of a "Guest" group?
The log instead follow to register the same error (ERROR 127.0.0.1	com_jcomments	Field 'object_params' doesn't have a default value). Probably that field is not filled at the moment of store the comment's data in the database. 
The field in the table's structure is set as not null but is of the type "text" and can't have a default value. But I don't understand the purpose of that field because is empty for all the records stored in the table #_jcomments...

**Comment by Globulopolis** [comment]
Guest user is not in public group. Select the default group for Guest in users component settings and set access rules in Jcomments for that group.

Field "object_params" is not used, and will be removed in next release.

**Comment by dangerx82** [comment]
Thank you guys! After the update of the 4.0.12 version everything works fine! No need of Guest group. It works like previous version for Joomla! 3.x
