### ISSUE TITLE
Timeline for Modules

### ISSUE THREAD

**Issue by iantrudell** [exstreme/Jcomments-4#47]
Hi all, do we have a timeline for when the JComments Latest, Latest Commented, Most Commented, Top Posters, and Latest Backend modules will be updated for Joomla 4, or a repo / branch where work has begun updating those? Thanks!

**Comment by exstreme** [comment]
Hello!
I think we need first update component code Jcomments with modern code style. Then we can update modules too. But may be @Globulopolis has another plans

**Comment by Globulopolis** [comment]
Hmmm... Just forgot about modules. I need some time to update them.

**Comment by Globulopolis** [comment]
@iantrudell see https://github.com/exstreme/Jcomments-4/tree/master/build/modules
