### ISSUE TITLE
Changing the title of objects did not work.

### ISSUE THREAD

**Issue by Globulopolis** [exstreme/Jcomments-4#50]
Steps to reproduce:
1. Change an article title on article with comments.
2. Go to `administrator/index.php?option=com_jcomments&view=comments`

Result: an old article title.
Manual fix: run `Refresh Objects`

Affected:
admin panel - all lists with comments and objects;
modules which displaying list of objects(articles, etc.);
user subscriptions, emails.

**Comment by exstreme** [comment]
https://github.com/exstreme/Jcomments-Recaptcha2/commit/69551fb0a66416279d649d23e1d039466e64c598 may be it can help
