### ISSUE TITLE
Migration issue 4.0.14

### ISSUE THREAD

**Issue by ThomDietrich** [exstreme/Jcomments-4#57]
Hey, sorry I can't name the issue better.
Thanks for maintaining this fork!

I started with an old export and your latest version 4.0.14. After installation of the plugin I imported my exported rows and end up with a working jcomments. irrespective of that, Joomla shows the following error:

![image](https://user-images.githubusercontent.com/2870104/153659088-d4a4dd01-f5de-44b4-bf60-bb6d35084954.png)

I did apply all migration steps from `4.0.12.sql` and `4.0.14.sql` but that doesn't change anything. Any help would be great.

Thanks and best!!

**Comment by exstreme** [comment]
Hello!
Can you check this files are identical:
https://github.com/exstreme/Jcomments-4/blob/master/component/administrator/install/sql/updates/mysql/4.0.12.sql
https://github.com/exstreme/Jcomments-4/blob/master/component/administrator/install/sql/updates/mysql/4.0.14.sql
Or simple overwrite it with files from repositary

**Comment by ThomDietrich** [comment]
Yes that solved it!
Does that mean there is a bug in the current release and you are going to publish a new release soon?

Thanks!

**Comment by ThomDietrich** [comment]
Will leave open till solved

**Comment by Globulopolis** [comment]
> Does that mean there is a bug in the current release and you are going to publish a new release soon?

Yes. We will release 4.0.15 asap.
