### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by ThomDietrich** [exstreme/Jcomments-4#59]
Hey guys,
I started to re-introduce german translation for this extension. Would you accept a PR?

**Comment by Globulopolis** [comment]
> Hey guys, I started to re-introduce german translation for this extension. Would you accept a PR?

Yes, why not :)

**Comment by ThomDietrich** [comment]
#66 still includes the "de/" and "ru/" files. I am not sure where those come from. Certainly not from the config I've uploaded through #65 and this isn't done through a rule in the crowdin UI

**Comment by ThomDietrich** [comment]
At least #66 also includes valid results now. Could it be that there are still other rules in place you did configure during setup of the project on crowdin. Would explain the use of `%two_letters_code%` which I didn't put anywhere

**Comment by exstreme** [comment]
fixed it

**Comment by ThomDietrich** [comment]
Nice
