### ISSUE TITLE
Show avatar next to article comments

### ISSUE THREAD

**Issue by ThomDietrich** [exstreme/Jcomments-4#60]
Hey friends,
I'm using latest versions of extension/plugins. The jcomments avatar plugin is installed and active but I can't enable it in the jcomments settings and no avatars are shown in comments list. Not sure how it should look, so here are some screenshots :) Some help would be appreciated!

![image](https://user-images.githubusercontent.com/2870104/154456388-0853647b-951f-409b-a4f1-11a8fac4b676.png)

![image](https://user-images.githubusercontent.com/2870104/154456301-c177876a-bcd1-461d-be06-17d237b8b149.png)

![image](https://user-images.githubusercontent.com/2870104/154456544-55377a4a-5782-413c-ae1b-d96cf89e3c45.png)

![image](https://user-images.githubusercontent.com/2870104/154456604-9dfa6499-73e2-422c-a48a-9ec20d79fa74.png)

**Comment by Globulopolis** [comment]
Plugins radio in component settings just tell the component to use plugins from /components/com_jcomments/plugins.
Avatar plugin is a component wide plugin. Go to Plugins - Jcomments avatar. Turn on, select the source and defaults.

**Comment by Globulopolis** [comment]
Can you provide a screenshot from frontend with comments list? Where an avatar must be 100%

**Comment by ThomDietrich** [comment]
Didn't quite understand you. Plugins -> Jcomments avatar is configured:

![image](https://user-images.githubusercontent.com/2870104/154567287-fd7f1c27-1a72-4980-b262-97eb89459015.png)

**Comment by ThomDietrich** [comment]
Taking it one step further, when I bypass the condition, `$comment->avatar` becomes "https://XXXXXXXXX.com/media/com_jcomments/images/no_avatar.png" for all comments. This does not change as I change the "Avatar Source" in the plugin settings.
