### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by Bavar2** [exstreme/Jcomments-4#70]
I tried to install version 4.15 on a clean version of Joomla 4.10 and this is what I get:

![obraz](https://user-images.githubusercontent.com/100325305/155436894-b601d3ce-3ecc-46fb-a5a5-1370bcec8c18.png)

Is there any solution to this?

**Comment by exstreme** [comment]
Version of SQL? And can you change it?

**Comment by Bavar2** [comment]
MySQL 5.6. Can't be change because it's hosting. Jcommnets version for Joomla 3.10.X working perfectly fine.
