### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by TORCommunity** [exstreme/Jcomments-4#71]
On installation of 4.0.16 (upgrade from 4.0.15), I'm getting this error:

```
Unexpected token < in JSON at position 0
```

**Comment by Globulopolis** [comment]
Please, provide a little bit more information.
PHP version, Joomla version?
Enable logging, see logs.

Because I cannot reproduce this issue on test.

**Comment by TORCommunity** [comment]
> Please, provide a little bit more information. PHP version, Joomla version? Enable logging, see logs.
> 
> Because I cannot reproduce this issue on test.

PHP 8.0.16, MySQL 8.0.28, Joomla 4.1.0

**Comment by exstreme** [comment]
Hello!
Can you turn on debug and max error displaying, and then check for response, which joomla  send via Ajax?

**Comment by Globulopolis** [comment]
Can't confirm this issue on J4.1, PHP 8.0.17
