### ISSUE TITLE
CSS Template Overrides in 4.0.17?

### ISSUE THREAD

**Issue by iantrudell** [exstreme/Jcomments-4#77]
With the CSS files moving from the tpl folder to media/com_jcomments/css, how do you change CSS on a per-template basis now?

I had a custom template with css in components/tpl/<custom_template_name>/style.css that no longer appears to load in 4.0.17

**Comment by Globulopolis** [comment]
> per-template basis now

What does it mean?
Custom component template or custom joomla template?
Copy files to new place.

It's a first step to move all component media to media folder to use with webassets manager.

**Comment by Globulopolis** [comment]
@iantrudell as a quick fix just copy css from this folder to media folder.

PS!
Web assets manager cannot load assets with dynamic paths. They all hardcoded in json file.
It's a long way to move from an old Joomla 1.5 code in component frontend to new Joomla 4 code, where we can use template/layout overrides in ROOT/tempates folder. Not in ROOT/component/ custom template.

**Comment by Globulopolis** [comment]
CSS now can be located at:
`ROOT/templates/{joomla_template_name}/html/com_jcomments/{jcomments_template_name}/`

and if not found search in

`ROOT/media/com_jcomments/css/tmpl/{jcomments_template_name}/`

PS! urls to images must be updated in CSS files.
