### ISSUE TITLE
Updating issue after 4.0.16

### ISSUE THREAD

**Issue by ThomDietrich** [exstreme/Jcomments-4#79]
Hey friends,
I can only assume this is due to the recent changes regarding css location? Can't figure out how to solve this. Any help would be much appreciated! Thanks

![image](https://user-images.githubusercontent.com/2870104/161437526-8a4ab916-5919-4837-b48d-4d9ce20f38be.png)

**Comment by Globulopolis** [comment]
> I can only assume this is due to the recent changes regarding css location

No. The installer does not copy file by file.

I tested package installation on clean Joomla 4.1.2.
Install 4.0.16 version and upgrade it to latest from web. No errors.

Please try to download package and install it via `Upload package file`.

**Comment by ThomDietrich** [comment]
Already tried this as well. Same error.
Is there a way to get more error verbosity than just "Copy file failed"?

If you can't come up with a reason I might take a backup of the database, then uninstall jcomments and install again.

**Comment by exstreme** [comment]
Can you check file permissions and owner on server?
