### ISSUE TITLE
Версия для сервера обновлений

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#82]
поставил  4.0.18
но система обновлений ругается:
<img width="1678" alt="Снимок экрана 2022-05-18 в 18 17 13" src="https://user-images.githubusercontent.com/3432048/169078811-1bbf2c77-3935-4d9f-bf30-77f314c69568.png">

нужно поправить файл для сервера обновлений

**Comment by Globulopolis** [comment]
@exstreme прийдет, пулреквест заведет, новую версию соберет.
