### ISSUE TITLE
Нет вкладка Права

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#84]
В версии под четверку нет вкладки права...

<img width="1247" alt="Снимок экрана 2022-05-18 в 21 14 12" src="https://user-images.githubusercontent.com/3432048/169115979-8db5237e-6edc-4b38-ba14-ea6993808960.png">

<img width="1573" alt="Снимок экрана 2022-05-18 в 21 14 00" src="https://user-images.githubusercontent.com/3432048/169115973-7a63811c-4393-4abf-b8e8-2e498b32363c.png">

**Comment by Globulopolis** [comment]
Там нет. Есть тут `administrator/index.php?option=com_config&view=component&component=com_jcomments`

**Comment by Sulpher** [comment]
Спасибо
