### ISSUE TITLE
Правила сайта не отображаются

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#85]
<img width="822" alt="Снимок экрана 2022-05-18 в 21 29 45" src="https://user-images.githubusercontent.com/3432048/169119112-0433d74a-886f-4103-87ae-ececaa8ec5ac.png">

показывать правила - все 
<img width="881" alt="Снимок экрана 2022-05-18 в 21 30 04" src="https://user-images.githubusercontent.com/3432048/169119160-bba498a7-753e-4c15-83f9-cce5e409581e.png">

поле с правилами заполнено.

правила не отображаются:
<img width="862" alt="Снимок экрана 2022-05-18 в 21 34 20" src="https://user-images.githubusercontent.com/3432048/169119319-2a66e27c-cf63-4b07-b8c5-99a353bb999a.png">

**Comment by Globulopolis** [comment]
Язык сайта какой?
Язык `Все` для сообщений используется если мультиязычность выключена или не настроены сообщения для других языков.

**Comment by Sulpher** [comment]
Русский язык на фронте, других нет.

**Comment by Globulopolis** [comment]
Попробуйте вместо Язык `Все` для сообщений выбрать Русский.

**Comment by Sulpher** [comment]
не помогло.
а у вас правила отображаются? интересно, баг в компоненте или настройки смотреть нужно.

**Comment by Globulopolis** [comment]
Нужно настройки смотреть. У меня отображается.

**Comment by exstreme** [comment]
Шаблон кастомный у Jcomments?

**Comment by Sulpher** [comment]
Шаблон default. кастомные от тройки валятся. 
Я ставил новую версию комментов после миграции J3 на J4. 
по идее, все правильно.
у контента нет даже выбора языка - мультиязычность выключена.

**Comment by exstreme** [comment]
Ну сходу только идея ACL настройки проверить

**Comment by Sulpher** [comment]
посмотрел я быстро код tpl_index.php
в старом шаблоне (кастомном) под тройку есть такой блок:

```
<?php
		if ($this->getVar( 'comments-form-policy', 0) == 1) {
?>
<div class="comments-policy"><?php echo $this->getVar( 'comments-policy' ); ?></div>
<?php
		}
?>
```
думаю, он был и в дефолтном.
в новом шаблоне под четверку и в tpl_index.php нет ничего похожего, ничего, связанного с privacy

либо переименовали, либо в другой файлик вынесли.. можете посмотреть на своей стороне?

**Comment by Sulpher** [comment]
нашел тут:
layouts/comments-form.php:

```
	<?php if ($displayData->getVar('comments-form-policy', 0) == 1): ?>
		<div class="border rounded comments-policy"><?php echo $displayData->getVar('comments-policy'); ?></div>
	<?php endif; ?>

```
самое интересное:  если удаляю условие и просто вывожу вот так по хардкору:
`		<div class="border rounded comments-policy"><?php echo $displayData->getVar('comments-policy'); ?></div>`
правила не отображаются, в коде ничего нет.  но если напишу 111 - выводится.
почему-то не срабатывает `<?php echo $displayData->getVar('comments-policy'); ?> `


 
вопрос: а переопределить шаблон комментов через шаблон Joomla можно?
смущает то, что часть верстки перенесена в com_jcomments/layouts/, а часть осталась в tpl

**Comment by Sulpher** [comment]
хмммм... чудеса. оказалось, что дело в неправильной миграции.
заменил вот этот файлик:
components/com_jcomments/jcomments.php на тот, что взят из дистрибутива и все заработало.

как это объяснить - непонятно. какие-то остатки от версии под тройку. 
по идее, при установке нового компонента должны были перезаписаться все файлы.

<img width="1297" alt="Снимок экрана 2022-05-19 в 08 25 13" src="https://user-images.githubusercontent.com/3432048/169217326-6ed64819-18db-4361-8506-1d19aba9a108.png">

посмотрел расширения, а там бардак:
<img width="1474" alt="Снимок экрана 2022-05-19 в 08 27 03" src="https://user-images.githubusercontent.com/3432048/169217349-74081dcc-3ace-4c55-91c1-c42bbf85923d.png">

обратите внимание на версию. 4.0.17  и 4.0.18
(после динсталляции и установки повторно та же картина)
вывод: миграция компонента с тройки на 4 прошла некорректно.
в общем, удалил компонент и поставил заново с переносом настроек. но теперь другие чудеса.

взгляните:
<img width="949" alt="Снимок экрана 2022-05-19 в 08 34 45" src="https://user-images.githubusercontent.com/3432048/169218257-2a8f4c00-610d-4903-84a1-f22a28cb85b5.png">

почему-то гостю стали отображаться все элементы:
включая кнопки действий модератора, хотя в правах такого не было.
теперь интересное:
<img width="890" alt="Снимок экрана 2022-05-19 в 08 36 20" src="https://user-images.githubusercontent.com/3432048/169218573-2822cc38-57db-4efa-adf3-e636b0b687ad.png">

я в настройках включаю отображение смайлов и доп.bbcode и они не отображаются на фронте. хотя появились оценки.
кэш сайта отключен, кэш браузера чистил.
<img width="966" alt="Снимок экрана 2022-05-19 в 08 44 04" src="https://user-images.githubusercontent.com/3432048/169218897-4b19bba0-c69e-423b-815a-485bef3fa246.png">

какая-то ерунда...

**Comment by Globulopolis** [comment]
Настройки как переносили? Если импорт/экспорт через компонент, то кривые настройки могли опять примениться. Настройки экспортируются вместе с правами.

**Comment by Globulopolis** [comment]
Теперь с правами... Если кнопки отобразились гостю, значит что-то не правильно в настройках прав.

**Comment by Sulpher** [comment]
ой, почему-то на фронте сайта авторизован как супер админ (хотя на фронте нет формы авторизации). 
поэтому и не думал посмотреть сюда. извините. разлогинился с фронта.
теперь почти все правильно.
правила сайта перестали отображаться. внимательно посмотрел  настройки:

вкладка права доступа - нет правила отображения правил
вкладка форма добавления комментариев - показывать правила - все
<img width="1245" alt="Снимок экрана 2022-05-19 в 09 03 01" src="https://user-images.githubusercontent.com/3432048/169221284-308892a6-c576-49ca-90b5-702da84bb825.png">

правила не отображаются гостю. когда был авторизован на фронте супер админом - они отображались.

настройки переносил через Json -= экспорт/импорт в компоненте.

**Comment by Globulopolis** [comment]
Вечером гляну, сейчас нет возможности.

**Comment by exstreme** [comment]
Предлагаю попробовать такое сделать.
Сделать бекап, удалить Jcomments и все его расширения (базу не трогать). И по новой накатить новую версию.
Проблема миграции в том, что раньше это был компонент со своим инсталятором, который на 4 криво работает, а следовательно нормально удалить не может. А теперь это пакет, который устанавливает на уровне джумлы все нужные расширения.

**Comment by Sulpher** [comment]
я уже так и сделал - удалил jcomments, поставил заново.
правда, json настройки импортировал.

в общем, развернул чистую Джумла 4.1, чистый JComments, создал один материал, подкрутил настройки.
вот что получилось:
<img width="1003" alt="Снимок экрана 2022-05-19 в 10 19 00" src="https://user-images.githubusercontent.com/3432048/169235195-26f5bcc8-82ca-4b1c-9d11-e5525484372d.png">

показывать правила: 
<img width="782" alt="Снимок экрана 2022-05-19 в 10 18 39" src="https://user-images.githubusercontent.com/3432048/169235240-fa20fb40-dfe4-4141-a0f1-5ca3800d4e13.png">
по умолчанию было Guest, выбрал вообще все группы, результата нет:
<img width="1054" alt="Снимок экрана 2022-05-19 в 10 18 52" src="https://user-images.githubusercontent.com/3432048/169235357-86a5fcea-b916-47dc-bf84-22e40f0ffa18.png">

однако, если авторизоваться супер админом, то правила отображаются:
<img width="1055" alt="Снимок экрана 2022-05-19 в 10 19 27" src="https://user-images.githubusercontent.com/3432048/169235412-c74a4f6a-160c-4437-a2c1-0f7863301ab3.png">

какой-то баг

**Comment by exstreme** [comment]
ПОдтверждаю, они отображаются у суперадмина даже если выставить только Public и Guest.
Будем смотреть вообщем
