### ISSUE TITLE
Плагин Система - Комментарии под Joomla 4

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#86]
В тройке есть плагин Система - Комментарии

заменяет вывод кнопки подробнее на свой блок с кол-вом комментов:
<img width="945" alt="Снимок экрана 2022-05-18 в 21 16 18" src="https://user-images.githubusercontent.com/3432048/169117089-20473ed2-c551-40e8-a5d6-5d8ee09eceb8.png">

на  четверке после миграции вот так:
<img width="981" alt="Снимок экрана 2022-05-18 в 21 16 48" src="https://user-images.githubusercontent.com/3432048/169117117-0ba8b6b8-3cef-44ec-8f16-3b5e76f59ab9.png">

не дописан функционал.

**Comment by Globulopolis** [comment]
В настройках плагина включите нужные переключатели.

![image](https://user-images.githubusercontent.com/740757/169135703-77de166b-c753-413d-82a6-e302d10faf8d.png)

**Comment by Sulpher** [comment]
Спасибо, я открыл не тот плагин (системный). фильтром искал по фразе jcomments.

в контент плагине вижу, под четверку меньше параметров.

планируете ли добавить недостающие из тройки?
<img width="1105" alt="Снимок экрана 2022-05-18 в 22 20 05" src="https://user-images.githubusercontent.com/3432048/169139613-83500ecf-220f-4010-9ee4-5656c05f2a6f.png">

**Comment by Sulpher** [comment]
и по внешнему виду вот как получается: 
<img width="515" alt="Снимок экрана 2022-05-18 в 22 23 42" src="https://user-images.githubusercontent.com/3432048/169140820-127671a4-5482-4107-a485-d3ad8dafe100.png">

предлагаю доработать  отображение в одну строку

**Comment by Globulopolis** [comment]
> планируете ли добавить недостающие из тройки?

нет, т.к. шаблон используется джумловский для отображения `Подробнее` + добавлен css класс `comments-readmore` для ссылки комментариев. Шаблон можно переназначить, а стили для ссылки добавить в css.

**Comment by Globulopolis** [comment]
> и по внешнему виду вот как получается:

вы можете сами это сделать через стили css.

**Comment by Globulopolis** [comment]
Попробуйте https://github.com/exstreme/Jcomments-4/raw/2eed1c2ac095ea046afe165a7718cf791799e354/build/packages/plg_content_jcomments.zip
Просто поверх перезалейте 3 файла links.php, jcomments.php, jcomments.xml
Должно помочь с отображением.

**Comment by Sulpher** [comment]
Накатил. теперь другое дело. спасибо!
<img width="923" alt="Снимок экрана 2022-05-19 в 09 06 17" src="https://user-images.githubusercontent.com/3432048/169222037-4a4e3d43-0cff-48d7-8adb-53eb78f361e4.png">

**Comment by Sulpher** [comment]
идея:
посмотрите на скрин выше - иногда нужно не только primary, то и просто button default поставить. 
не хочется переопределять шаблон для плагина. 
предлагаю внести параметр: класс кнопки.

**Comment by Globulopolis** [comment]
> идея:
> посмотрите на скрин выше - иногда нужно не только primary, то и просто button default поставить. 
> не хочется переопределять шаблон для плагина. 
> предлагаю внести параметр: класс кнопки. 
> 
> 
> 

Макет ссылок на комментарии сделан в одном стиле с макетом "Подробнее" в Джумле.

**Comment by Vigoleto** [comment]
"Comments" link in the list of Featured Articles doesn't seem to work. I still got “read more” button in my homepage. And of course, I have two read more buttons. Any solution?


![Crop It 2024-4-20 at 10 13 54](https://github.com/exstreme/Jcomments-4/assets/159842854/347a7ad5-470b-4303-ba63-7cb7d259f7f2)
![Crop It 2024-4-20 at 10 14 19](https://github.com/exstreme/Jcomments-4/assets/159842854/84b5f9b3-ca51-4545-9a74-f76761a15c37)

**Comment by Globulopolis** [comment]
@Vigoleto I cannot reproduce the issue.
Do you have caching enabled?

**Comment by Vigoleto** [comment]
Hello sir
Not that I know of.
It was a long journey migrating form Joomla 2.5 to 4.4.4, maybe I mess something up. :(
Here is all the Jcomments in the Extensions Manager, maybe I did leave some old stuff? 
I’m using Yootheme pro – just figuring out how it works, I don’t know if its related.
The site address is https://3joomlabackup.forumat-bg.com/ if that helps in some way

![Crop It 2024-4-21 at 13 17 10](https://github.com/exstreme/Jcomments-4/assets/159842854/0eae9478-0a97-4673-92bd-800d112a22f6)

**Comment by Globulopolis** [comment]
@Vigoleto that yootheme pro template you are using?

**Comment by Vigoleto** [comment]
@Globulopolis Yes, I’m using yootheme pro template
Do you think that the theme is causing the problem?

**Comment by Globulopolis** [comment]
> @Globulopolis Yes, I’m using yootheme pro template
> Do you think that the theme is causing the problem?
> 

Maybe. Try switch to default joomla template.

**Comment by Vigoleto** [comment]
@Globulopolis Ok, I did some testing as you kindly suggested.

1.	In Cassiopeia - no extra related article buttons on the front page.
2.	If I disable the “Content - Comments Jcomments “ Plugin and use Yootheme - no extra related article buttons on the front page.

So somehow the Yootheme overrides the rule - “Comments link in the list featured articles”.
If I understand correctly, looking through the class “btn.btn-secondary”, the extra button is displayed as a secondary button.
Maybe I could edit my theme articles.php so that that secondary button wont display. But I don’t know what to look for. I know is too much to ask for further help, but can you point me to the right direction?

**Comment by Globulopolis** [comment]
@Vigoleto I need some time to find solution for this issue.

**Comment by Vigoleto** [comment]
@Globulopolis Thank you kindly for looking in to it

**Comment by Globulopolis** [comment]
@Vigoleto see https://github.com/exstreme/Jcomments-4/issues/165#issuecomment-2092577614
