### ISSUE TITLE
Only one subscription is visible in administration panel

### ISSUE THREAD

**Issue by zavlab1** [exstreme/Jcomments-4#92]
https://github.com/exstreme/Jcomments-4/blob/master/component/administrator/views/subscriptions/tmpl/default.php

Думаю, <?php endforeach; ?> надо переместить с 80-й на 123-ю строку, иначе отображается только одна подписка из всего списка.

**Comment by exstreme** [comment]
Hello! Thank you! Fixed in https://github.com/exstreme/Jcomments-4/commit/dce39880b425cc266b9b76276f79788a8d5258e7
