### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by phnoel** [exstreme/Jcomments-4#93]
Hi!
Please, how to resolve this ?
Notice: Undefined index: * in C:\xampp\htdocs\weblim\components\com_jcomments\cl asses\text.php on line 187

Notice: Trying to get property 'message_policy_whocancomment' of non-object in C:\xampp\htdocs\weblim\components\com_jcomments\cl asses\text.php on line 187

Many thanks

**Comment by Globulopolis** [comment]
@phnoel replace file in your installation from this https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/text.php and let me know if issue is fixed.

**Comment by phnoel** [comment]
Sorry, it doesn't work: I get a helix Class 'JComments' not found error.

I modified the jcomments.php file in the com_jcomments folder. Was it the right one?


De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] Notice (Issue #93)
Date : 03/06/2022 16:23:00 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


@phnoel replace file in your installation from this https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/text.php and let me know if issue is fixed.

**Comment by Globulopolis** [comment]
> I modified the jcomments.php file in the com_jcomments folder. Was it the right one?

No.  Download this file https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/text.php and put into `C:\xampp\htdocs\weblim\components\com_jcomments\classes\` with replace.

**Comment by phnoel** [comment]
OK, tank you Vladimir, but what file to replace ?



De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] Notice (Issue #93)
Date : 03/06/2022 18:32:24 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


I modified the jcomments.php file in the com_jcomments folder. Was it the right one?

No. Download this file https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/text.php and put into C:\xampp\htdocs\weblim\components\com_jcomments\classes\ with replace.

**Comment by Globulopolis** [comment]
> but what file to replace

text.php

**Comment by phnoel** [comment]
Sorry, it still doesn't work! The form (top of page) is not displayed




De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] Notice (Issue #93)
Date : 03/06/2022 23:13:16 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


but what file to replace

text.php

**Comment by Globulopolis** [comment]
> Sorry, it still doesn't work! The form (top of page) is not displayed
> 
> 
The form or notice? We talk about notice. If form not displayed, when check the access rights in component settings.

**Comment by phnoel** [comment]
OK, thank you, by changing the rights the form is displayed well now, but I still get these messages :

Notice: Undefined index: * in C:\xampp\htdocs\weblim\components\com_jcomments\classes\text.php on line 187
Notice: Trying to get property 'message_policy_post' of non-object in C:\xampp\htdocs\weblim\components\com_jcomments\classes\text.php on line 187



Does it matter? If I set the Error Report to "none" they still show up?


De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] Notice (Issue #93)
Date : 04/06/2022 11:55:51 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


Sorry, it still doesn't work! The form (top of page) is not displayed

The form or notice? We talk about notice. If form not displayed, when check the access rights in component settings.

**Comment by Globulopolis** [comment]
@phnoel maybe.
Have you replaced the file that I mentioned above?

**Comment by phnoel** [comment]
of course !
this one :  https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/text.php

here  : C:\xampp\htdocs\weblim\components\com_jcomments\classes\text.php


De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] Notice (Issue #93)
Date : 04/06/2022 13:56:23 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


@phnoel maybe.
Have you replaced the file that I mentioned above?

**Comment by Globulopolis** [comment]
Try to add messages for language 'All' on 'Messages' tab in component settings.

**Comment by phnoel** [comment]
Really sorry, but I can't find the "Messages" tab in the component settings.

I have "comment list" and "comment window settings" and nothing in there related to language.

Can you take a screenshot for me? Many thanks



De : Vladimir ***@***.***>
À : exstreme/Jcomments-4 ***@***.***>
Sujet : Re: [exstreme/Jcomments-4] Notice (Issue #93)
Date : 04/06/2022 14:51:55 Europe/Paris
Copie à : phnoel ***@***.***>;
   Mention ***@***.***>


Try to add messages for language 'All' on 'Messages' tab in component settings.

**Comment by Globulopolis** [comment]
> Can you take a screenshot for me? Many thanks

![image](https://user-images.githubusercontent.com/740757/172019988-68c27ba3-c962-48a2-8b65-f566e261a6eb.png)

**Comment by Globulopolis** [comment]
@phnoel redownload file from https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/classes/text.php and replace in your folder `C:\xampp\htdocs\weblim\components\com_jcomments\classes\text.php`
This should fix the notice.
