### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by phnoel** [exstreme/Jcomments-4#95]
Hi ! how to complete the french translation ?
Which file should be modified ?
![jcomments](https://user-images.githubusercontent.com/106807928/174446514-4f10c9c0-3527-44e2-8e17-5e03f5391b75.jpg)
Many thanks

**Comment by exstreme** [comment]
Hello! override in your language folder (language/{lang alias}/{lang alias}.com_jcomments.ini)or in backend area https://github.com/exstreme/Jcomments-4/blob/master/component/site/language/en-GB/com_jcomments.ini

**Comment by phnoel** [comment]
Perfect, many thanks.
I noticed another anomaly: the fields of are reset to zero after sending the comment...
![jcom](https://user-images.githubusercontent.com/106807928/174577214-b85939ba-7555-4e10-9508-9f054449ab02.jpg)

**Comment by exstreme** [comment]
Default template or custom, have you seen any JavaScript errors?

**Comment by phnoel** [comment]
No, no display errors !
The errors report of Joomla is at "maximum".

**Comment by exstreme** [comment]
Link on example?

**Comment by phnoel** [comment]
https://weblim.go.yo.fr/avis

**Comment by exstreme** [comment]
hmm, and why they should be reseted? It isn't bug

**Comment by phnoel** [comment]
Well, I thought it was normal for the form fields to be emptied after submission. Isn't this the usual way?
If not, can we put a redirection on another page after the comment is taken into account?

**Comment by phnoel** [comment]
OK,
To thank you, here is the translation file for French
[com_jcomments.zip](https://github.com/exstreme/Jcomments-4/files/8950408/com_jcomments.zip)
