### ISSUE TITLE
Не поддерживает hCaptcha

### ISSUE THREAD

**Issue by joomlovod** [exstreme/Jcomments-4#98]
В настройках выбрать можно, но при просмотре статьи появляется ошибка 0, плагин не найден.
Было бы здорово, если бы JComments поддерживал hCaptcha. Спасибо!

**Comment by Globulopolis** [comment]
@joomlovod замените 2 файла у себя:
`components/com_jcomments/jcomments.php` на файл https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/jcomments.php
и `components/com_jcomments/layouts/comment-form.php` на файл https://raw.githubusercontent.com/Globulopolis/Jcomments-4/master/component/site/layouts/comment-form.php

Должно помочь.

**Comment by joomlovod** [comment]
Теперь всё отлично! Бесконечная благодарность вам!
